### ISSUE TITLE
In order to using tree-shaking

### ISSUE THREAD

**Issue by sculove** [naver/egjs-view360#128]
@sculove commented on [Tue Jan 16 2018](https://github.com/naver/egjs-flicking/issues/72)

## Description
Axes supports ES6 Module for Tree-shaking.
if you want to use latest version of `@egjs/axes`, you should change code following like

#### AS-IS (before `@egjs/axes` v2.4.2)
```js
import Axes from "@egjs/axes";

// new Axes()
// new Axes.PanInput()
```

#### TO-BE (after `@egjs/axe`s v2.4.2)
```js
import Axes, {PanInput} from "@egjs/axes";

// new Axes()
// PanInput()
```

**Comment by jongmoon** [comment]
We applied it after 2.0.3 and 3.0.0
