### ISSUE TITLE
Test cross browsing of v3.0.0-rc

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-view360#136]
## test subject
* cubemap rendering
* equirectangular rendering

### desktop
- [x]   IE11
- [x]   MS EDGE
- [x]   Safari
- [x]   Firefox
- [x]   Chrome

### iOS
- [x]  iOS 8 safari
- [x]  iOS 9 safari
- [x]  iOS 10 safari
- [x]  iOS 11 safari 

### iOS: Unstable device
* iPad mini 2, iOS 9.2, safari
* iPhone 5, iOS 9.1, safari

### Android: Unstable device
* Galaxy S8, Samsung Internet
* Galaxy S6, android 5.0.2, Samsung Internet
* Galaxy S5, android 5.0, Samsung Internet
* Galaxy Note5, android 5.1.1, Samsung Internet 3.x
* Galaxy Note5, android 5.1.1, Samsung Internet 4+
* LG V10, android 6.x, Chrome
* LG G5, android 6.x, Chrome

**Comment by jongmoon** [comment]
## Test

1. test/manual/PanoViewer/PanoViewer.html
2. default (cube) mode
   1. Test if it is rendered
3. change 360_equirectangular mode
   1. Test if it is rendered

### Window

#### Windows 7(Pararelles)

| ser \ Mode | Equirectangular | Cube |
| ---------- | --------------- | ---- |
| IE 11      | O               | O    |

#### Window 10

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| IE 11          | O               | O    |
| Edge           | O               | O    |


### iOS

#### iOS 8

iPhone 5

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Safari         | X               | O    |
| NAVER          | X               | O    |
| Chrome         | X               | O    |

![image](https://user-images.githubusercontent.com/3255471/38005389-6102ed9e-327b-11e8-9d0b-c3fe5891bcc5.png)


#### iOS 9

iPhone 5S

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Safari         | O               | O    |
| NAVER          | O               | O    |
| Chrome 47      | O               | O    |

#### iOS 10

iPhone 7+, iOS 10.2

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Safari         | O               | O    |
| NAVER          | O               | O    |
| Chrome         | O               | O    |

#### iOS 11

iPad 2 Pro

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Safari         | O               | O    |
| NAVER          | O               | O    |
| Chrome         | O               | O    |

### Android: Unstable device

Following Device/Browser has been reported not working properly in View360 1.0 version

#### Galaxy S8

| Browser \ Mode       | Equirectangular | Cube |
| -------------------- | --------------- | ---- |
| Samsung Internet 6.4 | O               | O    |
| Chrome 65            | O               | O    |
| NAVER 8.5.1          | O               | O    |

#### Galaxy S6(Android 5.0.2)

| Browser \ Mode   | Equirectangular    | Cube                       |
| ---------------- | ------------------ | -------------------------- |
| Samsung Internet | `X` (Black Screen) | `X` (2 Wide Box in 1 Area) |
| Chrome 65          | O        | O                |

![image](https://user-images.githubusercontent.com/3255471/38005813-5f8b28da-327d-11e8-906b-4c32a7f13a44.png)


#### Galaxy S5 (Android 5.0)

| Browser \ Mode   | Equirectangular | Cube                |
| ---------------- | --------------- | ------------------- |
| Samsung Internet | O               | `X` (patched style) |
| Chrome (ver 39)  | O               | O                   |

![image](https://user-images.githubusercontent.com/3255471/38005486-c5144026-327b-11e8-9ec5-ca5b901e868c.png)

#### Galaxy Note 5 (Android 5.1.1)

> Unavailable

| Browser \ Mode       | Equirectangular | Cube |
| -------------------- | --------------- | ---- |
| Samsung Internet 3.x |                 |      |
| Samsung Internet 4+  |                 |      |

#### LG V10 (Android 6.x)

> Unavailable

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Chrome         |                 |      |

#### LG G5 (Android 6.x)

> Unavailable

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Chrome         |                 |      |

### iOS: Unstable device

Following Device/Browser has been reported not working properly in View360 1.0 version

#### iPad mini 2 (iOS 9.2)

We can only get iPad mini2 with iOS 9.1. Following results are tested on 9.1

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Safari         | O               | O    |

#### iPhone 5 (iOS 9.1)

> Unavailable

| Browser \ Mode | Equirectangular | Cube |
| -------------- | --------------- | ---- |
| Safari         |                 |      |

**Comment by jongmoon** [comment]
## Test Failed

### iOS

  - iPhone 5, iOS 8, Safari/Chrome (Equirectangular is not working)

### Android

  - Galaxy S6, Android 5.0.2, Samsung Internet 3 (latest is 6)
  - Galaxy S5, Android 5.0, Samsung Internet 3 (Cube is not working)

## Not tested

Cannot acquired

  - Note5 Android 5.1.1
  - LG V10 Android 6
  - LG G5 Android 6
  - iPhone 5, iOS 9

## Reported Unstable But working well
 
  - Galaxy S8
  - iPad mini2 (But minor version is different from reported version)

**Comment by jongmoon** [comment]
Tests Failed on Android is related with  #147

**Comment by jongmoon** [comment]
This issues will be continued on #191
