### ISSUE TITLE
Equirectangular mode(PanoViewer manual test) does not work on mobile browser.

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs-view360#138]
## Description

When changed to equirectangular mode, it does not render. it shows black area.

## Steps to check or reproduce
  - /test/manual/PanoViewer/PanoViewer.html
  - change mode to equirectangular
  
I tested on Android 6(Note4), iPad Pro 10.1 (iOS11)

**Comment by happyhj** [comment]
Yes, test image change is applied to this PR.
https://github.com/naver/egjs-view360/pull/145
