### ISSUE TITLE
Can not play video with PanoViewer at IE11

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-view360#144]
## Description
I am testing the video playback feature of 3.0.0-rc on Internet explorer 11.
And it seems to give me some errors.

Errors:
<img width="619" alt="screen shot 2018-02-06 at 6 14 15 pm" src="https://user-images.githubusercontent.com/3903575/35851014-01432640-0b6a-11e8-9fbf-9c522e52df1b.png">

It issue seems related with this.
https://github.com/mrdoob/three.js/issues/7560

**Comment by jongmoon** [comment]
@happyhj There may be two action for this.

1. Replace video in texImage2d with canvas
  - Best
2. Fire event("NOT SUPPORTED")... 

How do you think about it?

**Comment by happyhj** [comment]
We should support 360-degree video playback for IE11.
So I will implement "1.Replace video in texImage2d with canvas" as soon as possible.
