### ISSUE TITLE
1x6 cubrstrip image rendered strangely

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-view360#147]
### environment
1. device 1
    * device: samsung galaxy s6
    * android: 5.0.1
    * browser: samsung internet (samsung browser) 3.0 
2. device 2
    * device: samsung galaxy note5
    * android: 5.1.1
    * browser: samsung internet (samsung browser) 3.4

### step
Initiate with `1x6 cubestrip` image with projectionType `cubemap`

**Comment by jongmoon** [comment]
It it better to handle this issue as reorganizing `Cube Map Shader`.
