### ISSUE TITLE
showing black after contentLoaded event when playing video 

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-view360#148]
### Environment
* Galaxy S6(5.0.1), Samsung Internet 3.0

### Steps
1. Initiate `PanoViewer` with video resource.
2. Play video after `contentLoaded` event triggered.

**Comment by jongmoon** [comment]
It's know issue. And we will not check video's playable status by pr (https://github.com/naver/egjs-view360/pull/157)

`contentLoaded` will be removed and `ready` will substitute for it. and `ready` event does not guarantee the playable status of video. So it will be needed to check playable status for PanoViewer initialzer.
