### ISSUE TITLE
android chrome 65+, view360's device motion does not work properly.

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs-view360#172]
## Description

After updating chrome 65, motion is not work properly. and we found the [same issue](https://github.com/immersive-web/webvr-polyfill/issues/307#issuecomment-373193093) has been handled in the **webvr-polyfill** library that we depend on. And there was big change on android chrome 65+ for `devicemotion`.(Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=805146)

Take a look at the relevant content and take appropriate action.

## Steps to check or reproduce

  - Update Android Chrome 65+
  - Enable gyro by `gyroMode:"VR"` or `gyroMode: "yawPitch"`(default).
  - Turn or move a device
    - It doesn't work properly on android Chrome 65, 66

**Comment by happyhj** [comment]
Chrome 65 don't provide deviceMotion's rotationRate value. 
But It fixed after 65.0.3325.148.

When GyroSensor is not available, we can use deviceorientation event instead.

**Comment by jsantell** [comment]
There are a few issues at play in Chrome 65 and 66; more details in the [0.10.3 release for webvr-polyfill](https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3). Hope this helps!

**Comment by jongmoon** [comment]
@jsantell I did not expect your feedback, and I am so grateful for the feedback. 
As you says, I'll check your release~ Thank you very much!
