### ISSUE TITLE
Hello, how can I use it? I need a document.

### ISSUE THREAD

**Issue by Rile14929** [naver/egjs-view360#187]
Hello, how can I use it? I need a document.

**Comment by jongmoon** [comment]
Thank you for your concern 👍 

We provide [PanoViewer Simple Guide](https://naver.github.io/egjs-view360/panoviewer.html), [SpinViewer Simple Guide](https://naver.github.io/egjs-view360/spinviewer.html) and  [API Doc](https://naver.github.io/egjs-view360/release/latest/doc/).

But currently **we are ready to open 3.0** version.
  - Video support, performance improvement, support additional gyro mode.
  - You can found more changes on this issue(#174)

There's some breaking changes on PanoViewer so we made [PanoViewer 3.0 UserGuide](https://github.com/naver/egjs-view360/wiki/PanoViewer-3.0-User-Guide)

Can I ask what component do you want to use? (PanoViewer or SpinViewer) If you answer me, I can help you more :)

**Comment by Rile14929** [comment]
谢谢,如果有什么疑问我会向你请教
Thank you. If you have any questions, I will consult you.

**Comment by jongmoon** [comment]
@Rile14929 OK, I'll be waiting for you~
