### ISSUE TITLE
Video Ended Event

### ISSUE THREAD

**Issue by Scaalees** [naver/egjs-view360#207]
Is there a video ended event that I can hook onto?

**Comment by jongmoon** [comment]
Unfortunately It is not supported. It doesn't control playback of video.

You can handle video event by getting video object by following.

```js
var video = panoViewer.getVideo();

video.addEventListner("ended", yourHandler);
```

**Comment by Scaalees** [comment]
Yeah, just losing my mind a little 😆

Cheers
