### ISSUE TITLE
Support Tree Shaking

### ISSUE THREAD

**Issue by younkue** [naver/egjs-view360#229]
## Description

Support Tree Shaking.
* update babel 7 and print pure label.

|target |kb|
|---|---|
|bundle|157kb|
|SpinViewer(webpack3)|148kb|
|SpinViewer(webpack4)|99kb|
|SpinViewer(webpack4 & no side effects)|56.2kb|
|PanoViewer(webpack3)|155kb|
|PanoViewer(webpack4)|144kb|

**Comment by jongmoon** [comment]
After applying tree shaking,
Compared to v3.1.0 build it's some saving although latest version has code increase.

|target |before size (kb)| after size(kb) |
|---|---|---|
|view360.pkgd.min.js| 190 | 184 |
|PanoViewer.pkgd.min.js | 182 | 178 |
|SpinViewer.pkgd.min.js | 70 | 69 |
