### ISSUE TITLE
Map alpha beta gamma to egjs yaw pitch

### ISSUE THREAD

**Issue by canado** [naver/egjs-view360#276]
Hi
let say I have a gyro view 360 in an iframe, I can retrieve all the gyro info from the parent page
alpha beta and gamma
I am trying to adjust the egjs-view360 accordingly with lootAt
but my values are a bit off, is there a nice way to convert the data to lookAt ?
or is there a another way to update the view with the parent page gyro
Thanks

**Comment by jongmoon** [comment]
@canado Thank you for your issue. 👍 

First I wonder why the gyro information should be transferred by parent? Is it different domain issue? Is `allow="gyroscope; accelerometer` on iframe not solution?

And currently It is unavailable. Conversion of Device motion to yaw/pitch is worked on YawPitchControl. But it's not exported and used internally.

We also consider to export this module but we should solved some issues for external use. 
If you have any question/opinion about this issue. Give feedback at any time.

**Comment by canado** [comment]
Hi Jongmoon

The problem is that the parent domain is different from the iframe domain, so the gyro/accelerometer can't be activated in the iframe. That is why I am passing the values alpha beta gamma through post messages from the parent page to the iframe.

But is there a method that can convert the data and then we pass it to lookAt ?
Because 
- 1 when I use 
PanoViewer.lookAt({yaw:beta ,pitch:90-alpha,fov:0},0); it is almost working, the values are a bit off and not as smooth as your live demo but still it is almost good
- 2 I am sure your plugin is using Device motion so in theory, it wouldn't be hard to make it work
( but I am not an expert : ))

Let me know
Thanks

**Comment by jongmoon** [comment]
@canado I understand your situation.
I've expected `iframe.setAttribute('allow', 'gyroscope; accelerometer');` would solve the problem.

 And using of alpha, beta, gamma values of `deviceorientation` is good try and it is the way we implement. But if you use only those value, then it works abnormally. For example **view360** accept yaw value as continual value. But gamma value is not continual, if you rotate right  you first get`0 ~ 90` but after you get `-90 ~ 0`degree.

It need some following conversion.

```js
   var PanoViewer = eg.view360.PanoViewer;
    var container = document.querySelector(".container");
    var panoViewer = new PanoViewer(container,{
        image: "../../img/equi.jpg",
        gyroMode: PanoViewer.GYRO_MODE.NONE
    });
    var degree = Math.PI / 180;

    var toRadian = function(a){
        return a * degree;
    }

    var toDegree = function(a){
        return a / degree;
    }

    var yaw = 0, pitch = 0;
    var curr = {};
    var diff = {};
    var prev = null;
    var out = document.getElementById("device-orientation-info");
    function deviceOrientationHandler(e) {
        rotateEuler({
            yaw: toRadian(e.alpha),
            pitch: toRadian(e.beta),
            roll: toRadian(e.gamma)
        }, curr);

        if (prev) {
            diff.yaw = curr.yaw - prev.yaw;
            diff.pitch = -(curr.pitch - prev.pitch);
        } else {
            diff.yaw = 0;
            diff.pitch = 0;
            prev = {};
        }

        prev.yaw = curr.yaw;
        prev.pitch = curr.pitch;
        prev.roll = curr.roll;
        
        window.requestAnimationFrame(function() {
            yaw += toDegree(diff.yaw);
            pitch += toDegree(diff.pitch);

            out.innerHTML = yaw;
            panoViewer.lookAt({yaw: yaw, pitch: pitch}, 0);
        });
    }

    if (window.DeviceOrientationEvent) {
        window.addEventListener("deviceorientation", deviceOrientationHandler, false);
    }

    // Taken from krpano's gyro plugin by Aldo Hoeben:
    // https://github.com/fieldOfView/krpano_fovplugins/tree/master/gyro/
    // For the math, see references:
    // http://www.euclideanspace.com/maths/geometry/rotations/conversions/eulerToMatrix/index.htm
    // http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToEuler/index.htm
    function rotateEuler(euler, result) {
        var heading, bank, attitude,
            ch = Math.cos(euler.yaw),
            sh = Math.sin(euler.yaw),
            ca = Math.cos(euler.pitch),
            sa = Math.sin(euler.pitch),
            cb = Math.cos(euler.roll),
            sb = Math.sin(euler.roll),

            matrix = [
            sh*sb - ch*sa*cb,   -ch*ca,    ch*sa*sb + sh*cb,
            ca*cb,              -sa,      -ca*sb,
            sh*sa*cb + ch*sb,    sh*ca,   -sh*sa*sb + ch*cb
            ]; // Includes 90-degree rotation around z axis

        /* [m00 m01 m02] 0 1 2
        * [m10 m11 m12] 3 4 5
        * [m20 m21 m22] 6 7 8 */

        if (matrix[3] > 0.9999)
        {
            // Deal with singularity at north pole
            heading = Math.atan2(matrix[2],matrix[8]);
            attitude = Math.PI/2;
            bank = 0;
        }
        else if (matrix[3] < -0.9999)
        {
            // Deal with singularity at south pole
            heading = Math.atan2(matrix[2],matrix[8]);
            attitude = -Math.PI/2;
            bank = 0;
        }
        else
        {
            heading = Math.atan2(-matrix[6],matrix[0]);
            bank = Math.atan2(-matrix[5],matrix[4]);
            attitude = Math.asin(matrix[3]);
        }

        result.yaw = heading;
        result.pitch = attitude;
        result.roll = bank;
    }

```

But it's not END. There are needed more consideration.

1. Initial Yaw, Pitch
2. Limit range of yaw, pitch
3. Touch Handling
4. More...

**YawPitchControl** is doing above but it's not exported. So you can not use it. 

Exporting that module would be considered.

**Comment by canado** [comment]
Hi @jongmoon 
Thank you so much for your quick reply. I have implemented the solution + I have specifically added the 
iframe.setAttribute('allow', 'gyroscope; accelerometer'); line for the parent page.

Now from within the iframe scope I have this warning
The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features

Do you think there is a way to enable it anyway ?

What I am gonna try is to move the converting ( values ) code from the iframe to the host page, and then post it to the iframe and do the lookAt.

I will let you know
