### ISSUE TITLE
Stereoscopic view / splitted canvas

### ISSUE THREAD

**Issue by canado** [naver/egjs-view360#278]
## Description
Is there an ETA on the stereoscopic view that will allow viewing through google cardboard for example.
like this here
https://threejs.org/examples/#webgl_effects_stereo

Thanks, 
BTW love this library very light very effective  smooth and without jQuery : )

**Comment by jongmoon** [comment]
@canado Thank you reporting again 👍 
Unfortunately, not yet . But we've planned to provide it until 3rd quarter of 2019.

**Comment by canado** [comment]
Thank you for your reply, do you think it would be easy to find a shortcut?
creating one div for left one for right with corresponding overflow:hidden values and a little separation in the middle ?

What do you think?

**Comment by jongmoon** [comment]
@canado Do you mean applying this [synchronize demo](https://naver.github.io/egjs-view360/examples/panoviewer/etc/synchronize.html) concept?

I think It may be possible to do it. By launch two panoviewer (with same equi image), one for the left and remain one for right and applying left eye offset and right eye offset on yaw.

For example like this. But I've not tried it.

```js
panoViewer1.on("viewChange", function(e) {
  // left eye offset
  var yaw = e.yaw + ....; //some value
  panoViewer2.lookAt({yaw: yaw, pitch: e.pitch, fov: e.fov});
});

panoViewer2.on("viewChange", function(e) {
  // right eye offset
  var yaw = e.yaw + ....; //some value
  panoViewer1.lookAt({yaw: yaw, pitch: e.pitch, fov: e.fov});
});
```

**Comment by huwllewellyn** [comment]
Can confirm this approach works perfectly

**Comment by jongmoon** [comment]
@huwllewellyn I expect so but I did not try it. Sorry that I can not confirm it.

**Comment by huwllewellyn** [comment]
@jongmoon If I create 2 panoViewers {video} it works well on Android and Desktop. But on iOS it seems you can only one canvas updates

**Comment by jongmoon** [comment]
@huwllewellyn I think [Synchronize demo](https://naver.github.io/egjs-view360/examples/panoviewer/etc/synchronize.html) is similar example and I've tested on IOS. It works well. :) If you show me the example you made I can help you more~

**Comment by huwllewellyn** [comment]
Yeah, I have no problems with images. But if you use a video as the source it does not seem to work

**Comment by huwllewellyn** [comment]
@jongmoon, did you manage to replicate this problem? Here is an example of it if you view on iPhone https://stileapp.com/simulations/v2/cosmos/vr-react/plant-cell/index.html

**Comment by huwllewellyn** [comment]
You can view the bug in prod here: https://stileapp.com/simulations/v2/cosmos/vr-react/mars/index.html

**Comment by jongmoon** [comment]
@huwllewellyn Great~ I can see it through cardbardVR.

Thank you for sharing your product here. 👍   I am so glad to see that view360 is used from outside of our company. But It seems that your share is image not video.

**Comment by huwllewellyn** [comment]
@jongmoon :o whoops. Try this one: https://stileapp.com/simulations/v2/cosmos/vr-react/plant-cell/index.html

I <3 what you're doing, thank you. I'm going to see if I can fix the problem and will PR if I find a solution.

**Comment by jongmoon** [comment]
@huwllewellyn 👍 I will wait for you.

**Comment by huwllewellyn** [comment]
@jongmoon Okay, I'm very confused. It looks like there is a bug in Safari desktop as well. If we use an HTML video as the source for both PanoView's we get a black canvas. 
<img width="840" alt="Screen Shot 2019-05-06 at 11 55 54 am" src="https://user-images.githubusercontent.com/6964021/57203738-eddf0f00-6ff5-11e9-9179-4aa8109a0b21.png">
But it works in chrome and FF!

Do you have any ideas why this might be the case?
