### ISSUE TITLE
Adding hotspots with projectionType equirectangular ?

### ISSUE THREAD

**Issue by canado** [naver/egjs-view360#279]
## Description
Would it be possible to add hotspots in a projectionType: "equirectangular" mode?
And these hotspots would follow the way the image is moving in 360?

Thanks

**Comment by jongmoon** [comment]
@canado Sorry for late. It's not supported as option. We've made [hotspot demo](https://github.com/naver/egjs-view360/issues/279). But `hotspot` is completely separated with PanoViewer. The feature was created using html.

You can reference that demo but its position is just approximate value. if you use it as a product it will feel insufficient. For more accurate position of hot spot, you will need a more job.

**Comment by rijn** [comment]
@jongmoon Thanks for the demo which is super helpful. I'm using this lib in production and I am a little bit lost about how to make the hotspot more accurate. Can you provide any clue?

**Comment by WoodNeck** [comment]
Hello @rjin!
If that "accurate" means hotspot's jiggling problem, check this issue: https://github.com/naver/egjs-view360/issues/310#issuecomment-604378183
