### ISSUE TITLE
Is there Any function available to get the data-yaw using mouse pointer.

### ISSUE THREAD

**Issue by upardhi** [naver/egjs-view360#287]
I am trying to get the data-yaw position according to the mouse courser available over the image. Can you please help me how can I do that?

The plugin is best but needs more tooling or documentation so that we can debug or contribute.

Please help me to find out the answer to this question.

**Comment by jongmoon** [comment]
@upardhi Unfortunately, it is not available currently. But I think it is good idea.

I didn't try it before. I think following method(not exaclty.) would be work. 

```js

const viewArea = document.querySelector("...");
panoviewer = new view360.PanoViewer(viewArea, {....});

viewArea.addEventListener("mousemove", e => {
  // get diff
  const diffY = currMousePos.x - prevMousePos.x;

  let yaw = panoviewer.getYaw() + diffY;
  panoviewer.lookAt({yaw}); // you may need to call it in requestAnimationFrame().
});


```

**Comment by upardhi** [comment]
Thank you!!

One more question. Is there a way to create a draggable element over the viewer so that the user can drag the object.
