### ISSUE TITLE
GyroMode isn't working in react app

### ISSUE THREAD

**Issue by swapnildubal** [naver/egjs-view360#288]
Hi,
I am facing issue with the gyromode. Below are the details
Packages:
 "@egjs/view360": "3.2.1",
"react": "^16.8.6",

CodeSnippet:

 useEffect(() => {
     const container = document.getElementById('target');
     new PanoViewer(container, {
      image: myImage,
      projectionType: "panorama",
      gyroMode: "yawPitch"
    });
  });

CSS:
#target {
  height: 100vh;
  position: relative;
}

Please let me know if there are any additional settings that I am missing out. Thanks.

**Comment by jongmoon** [comment]
@swapnildubal Your setting is good!

Is the follow example works? 
  - https://naver.github.io/egjs-view360/examples/panoviewer/projection-type/panorama_image.html

If it doesn't work also I wonder if your gyro is available in your phone. If it works...can you share your example?

**Comment by swapnildubal** [comment]
@jongmoon the example works fine on my cellphone, however my code doesn't.
Below is the entire component code:

import React, {useEffect, useRef} from 'react';
import { PanoViewer } from '@egjs/view360';
import myImage from './assets/images/newpano.png';

function PanoComponent() {
  const panoContainer = useRef();
  useEffect(() => {
     const container = document.getElementById('target');
     new PanoViewer(container, {
      image: myImage,
      projectionType: "panorama",
      gyroMode: "yawPitch"
    });
  });
  return(
    <div id="target" ref={panoContainer}>
     </div>
  )
}

export default PanoComponent;

**Comment by jongmoon** [comment]
@swapnildubal Sorry, I couldn't find what is wrong. Could you provide me a working example on code playground like [codesandbox](https://codesandbox.io/dashboard). It would be helpful to analysis the problem.

**Comment by swapnildubal** [comment]
@jongmoon The thing is its not working in my local , I tried to connect to my machine from my cellphone with the IP address. However, when I deployed it to heroku(having a domain name and not ip) it worked. Couldn't understand the reason. Did anyone face this issue earlier?

**Comment by jongmoon** [comment]
@swapnildubal I found the reason why it is not working. 

https://github.com/aframevr/aframe/issues/4179

Recently in Safari, Chrome,  `devicemotion` is only woking on https(secure) origin.  So it will be not working on `http` like `http://localhost`.

**Comment by swapnildubal** [comment]
Okay, this helps. 
Thank you
