### ISSUE TITLE
Adding hotspot to projectionType panorama is possible?

### ISSUE THREAD

**Issue by bulesz** [naver/egjs-view360#289]
Hello,

Is it possible to adding hotspots to the photo as moving layer? (folowing the panoramic photos position)

?

Something similar to the HotSpot demo, but with panorama projectionType.

Many thanks,
Bulcsu

**Comment by WoodNeck** [comment]
Hello @bulesz,

It is possible to add hotspots to a panorama, but I'm sorry to say that it isn't part of view360's features.

As you can see in the [code of HotSpot demo](https://github.com/naver/egjs-view360/blob/master/demo/examples/panoviewer/etc/hotspot.html#L325), that demo is actually made by using view360's internal values.

So, if you use the same codes(of course you can customize it) in the demo, you can make the same thing in panorama projection like [this](https://codepen.io/woodneck/pen/WNepXNv).

**Comment by bulesz** [comment]
Thank you for your kind help!
