### ISSUE TITLE
Will egjs support little planet animation effect in the future?

### ISSUE THREAD

**Issue by HypnosNova** [naver/egjs-view360#295]
## Description
We found that  may panorama library(such as Krpano) support "Little planet" effect looks like the following image:
![image](https://user-images.githubusercontent.com/7953802/67999145-fdce6780-fc95-11e9-8d0f-b3ceaaac4ca5.png)
 
And we want to add this effect into our project and our project is using egjs. So is there any tutorial for adding this effect in egjs  or will egjs support the effect later?

**Comment by WoodNeck** [comment]
Hello @HypnosNova!
Unfortunately, that kind of effect is not supported at the moment.
I think that's pretty cool effect to implement, but even if we're going to work on it, you have to wait quite a long time as we're currently working on the stereo renderer first.
Anyway, thanks for the great idea!
