### ISSUE TITLE
not working in popup

### ISSUE THREAD

**Issue by getvivekjoshi** [naver/egjs-view360#300]
somehow onclick bootstrap popup scroll image not visible

**Comment by WoodNeck** [comment]
Hello, @getvivekjoshi!
Can you provide some demo to reproduce so I can work on it? :)

**Comment by getvivekjoshi** [comment]
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>PanoViewer examples</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/demo.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="js/view360.pkgd.js"></script>
</head>

<body>
  <a href="#" data-toggle="modal" data-target="#myModalZoom">
      Popuo                                                  
</a>
													
													    
    <div class="modal" id="myModalZoom">
        <div class="modal-dialog">
            <div class="modal-content">

                
                <div class="modal-header">

                    <a class="close" data-dismiss="modal">&times;</a>
                </div>

                
                <div class="modal-body">
                    <div id="myPanoViewer" class="viewer"></div>

                </div>

                


            </div>
        </div>
    </div>
												
    <section>
           
			 <div id="myPanoViewer1" class="viewer"></div>
    </section>
   
    <script>
    // create PanoViewer with option
    var PanoViewer = eg.view360.PanoViewer;
    var container = document.getElementById("myPanoViewer");
        
    var panoViewer = new eg.view360.PanoViewer(
        container,
        {
            image: "img/download.png",
            yaw: 45, // not mandatory, default value is 0.
            pitch: 13, // not mandatory, default value is 0.
            fov: 110 // not mandatory, default value is 65.
        }
    );
	
	 // create PanoViewer with option
    var PanoViewer = eg.view360.PanoViewer;
    var container = document.getElementById("myPanoViewer1");
        
    var panoViewer = new eg.view360.PanoViewer(
        container,
        {
            image: "img/pano_4096.jpg",
            yaw: 45, // not mandatory, default value is 0.
            pitch: 13, // not mandatory, default value is 0.
            fov: 110 // not mandatory, default value is 65.
        }
    );
</script>

</body>

</html>

**Comment by getvivekjoshi** [comment]
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>PanoViewer examples</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/demo.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="js/view360.pkgd.js"></script>
</head>

<body>
  <a href="#" data-toggle="modal" data-target="#myModalZoom">
      Popuo                                                  
</a>
													
													    
    <div class="modal" id="myModalZoom">
        <div class="modal-dialog">
            <div class="modal-content">

                
                <div class="modal-header">

                    <a class="close" data-dismiss="modal">&times;</a>
                </div>

                
                <div class="modal-body">
                    <div id="myPanoViewer" class="viewer"></div>

                </div>

                


            </div>
        </div>
    </div>
												
    <section>
           
			 <div id="myPanoViewer1" class="viewer"></div>
    </section>
   
    <script>
    // create PanoViewer with option
    var PanoViewer = eg.view360.PanoViewer;
    var container = document.getElementById("myPanoViewer");
        
    var panoViewer = new eg.view360.PanoViewer(
        container,
        {
            image: "img/download.png",
            yaw: 45, // not mandatory, default value is 0.
            pitch: 13, // not mandatory, default value is 0.
            fov: 110 // not mandatory, default value is 65.
        }
    );
	
	 // create PanoViewer with option
    var PanoViewer = eg.view360.PanoViewer;
    var container = document.getElementById("myPanoViewer1");
        
    var panoViewer = new eg.view360.PanoViewer(
        container,
        {
            image: "img/pano_4096.jpg",
            yaw: 45, // not mandatory, default value is 0.
            pitch: 13, // not mandatory, default value is 0.
            fov: 110 // not mandatory, default value is 65.
        }
    );
</script>

</body>

</html>

**Comment by getvivekjoshi** [comment]
Hi @WoodNeck, 
I have added code used bootstrap popup, inserted the  myPanoViewer but the image is not visible, I need to show 360 view in popup.
Thanks,
Vivek

**Comment by WoodNeck** [comment]
I've just checked your demo and it looks like the height is set to 0 because of modal CSS that prevents calculation of View360's size.
You can simply do that by setting width/height values to element, and also in options.

```diff
<div class="modal-body">
+ <div id="myPanoViewer" class="viewer" style="width: 300px; height: 300px;"></div>
</div>
```

```diff
    var panoViewer = new eg.view360.PanoViewer(
        container,
        {
            image: "https://i.imgur.com/4AiXzf8.jpg",
+           width: 300,
+           height: 300,
            yaw: 45, // not mandatory, default value is 0.
            pitch: 13, // not mandatory, default value is 0.
            fov: 110 // not mandatory, default value is 65.
        }
    );
```

**Comment by getvivekjoshi** [comment]
@WoodNeck  thanks its working fine I am closing the issue, I used another way, onclick I applied settimeout function and set time 250 milli secons and its working.
