### ISSUE TITLE
problem regarding where to take input. 

### ISSUE THREAD

**Issue by kumarshubh707** [naver/egjs-view360#303]
kindly explain where to provide input image/video. Also provide the detail of how to get output. It will helpful for us as we are unable to proceed. 
Thank you

**Comment by WoodNeck** [comment]
Hello, @kumarshubh707!
There's our guide about how to load image & video on the Wiki page.
https://github.com/naver/egjs-view360/wiki/PanoViewer-3.0-User-Guide
Please contact me if you still need help :)

**Comment by kumarshubh707** [comment]
I am still not getting where to give input image in code and how & where
should I expect output.

**Comment by WoodNeck** [comment]
You can see the demos here: https://naver.github.io/egjs-view360/panoviewer.html
Each demos include source code of it, so you can take any of those for starter template I guess.
