### ISSUE TITLE
High resolution images (from Insta360 one x)

### ISSUE THREAD

**Issue by msmuller** [naver/egjs-view360#304]
## Description

When I use a image direkte from my Insta 360 one X, it will not display on a IO device (iPhone 11 Pro and iPad Pro)

The image is 6080x3040 - if I downscale it to 2400x1200 it will display fine

There is no problem in IE, Chrome, Edge or Opera.

Is the a setup issuse ??

## Steps to check or reproduce

Use simple code:

&lt;!DOCTYPE HTML&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /&gt;
    &lt;meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"&gt;
    &lt;title&gt;A simple example &aelig;&oslash;&aring;&lt;/title&gt;

    &lt;link rel="stylesheet" type="text/css" href="./css/demo.css"&gt;
    &lt;link rel="stylesheet" type="text/css" href="./css/PanoControls.css"&gt;
    &lt;script src="./js/jquery-2.2.4.js"&gt;&lt;/script&gt;
    &lt;script src="./js/screenfull.min.js"&gt;&lt;/script&gt;
    &lt;script src="./js/PieView.js"&gt;&lt;/script&gt;
    &lt;script src="./js/view360.pkgd.js"&gt;&lt;/script&gt;
    &lt;script src="./js/PanoControls.js"&gt;&lt;/script&gt;

    &lt;style&gt;
    &lt;/style&gt;
&lt;/head&gt;

&lt;body&gt;
&lt;p&gt;test &lt;? echo date("d-m-Y H:i:s");?&gt;&lt;/p&gt;
&lt;div class="viewer" id="myPanoViewer"&gt;&lt;/div&gt;
&lt;script&gt;
	// https://naver.github.io/egjs-view360/examples/panoviewer/controls/custom-control.html
	// https://naver.github.io/egjs-view360/panoviewer.html
	// https://naver.github.io/egjs-view360/release/latest/doc/eg.view360.PanoViewer.html
	// https://github.com/naver/egjs-view360/wiki/PanoViewer-3.0-User-Guide

	var PanoViewer = eg.view360.PanoViewer;
	
	// create PanoViewer with option
	var container = document.getElementById("myPanoViewer");
	var panoViewer = new eg.view360.PanoViewer(container, {
			image: "./test-lq2.jpg",
			projectionType: "PanoViewer"
	});

	container.focus();

	PanoControls.init(container, panoViewer);
	PanoControls.showLoading();
	
        
&lt;/script&gt;

&lt;/body&gt;
&lt;/html&gt;

**Comment by WoodNeck** [comment]
Hello, @msmuller!
The maximum texture(image) size depends on the GPU.
By that, mobile devices have less maximum texture size generally.
Normally 4096 * 4096 is maximum for the mobile devices, and I heard that some iOS devices have 2048 * 2048 as maximum.
So, you can take the minimum image size for your supported devices, or you can prepare multiple images by size, and take the maximum size possible.
You can query maximum texture size like the following:
```js
gl.getParameter(gl.MAX_TEXTURE_SIZE); // Suppose gl is WebGLRenderingContext
```
PanoViewer doesn't provide an API for accessing internal canvas & WebGL context.
So you can make canvas element yourself then grab context, or you can access internal value like this:
```js
var panoViewer = new eg.view360.PanoViewer(container, {
  projectionType: "panorama",
  image: "./img/panorama.jpg"
});

var gl = panoViewer._photoSphereRenderer.context;
```
But, be sure that internal structure can be changed anytime at the next version :)

**Comment by msmuller** [comment]
Thanks, that worked perfect :)
