### ISSUE TITLE
PanoViewer Not working in IE11

### ISSUE THREAD

**Issue by dansundy** [naver/egjs-view360#307]
## Description
I am getting an error "Const bust be initialized" in IE11 even when using the ES5 initialization method. It looks like it is happening due to a `for..in` method with a `const` in it. Is IE11 not supported?

Here is the URL I am using: `//naver.github.io/egjs-view360/release/latest/dist/PanoViewer/view360.panoviewer.pkgd.min.js`

## Steps to check or reproduce
Put the following in the head of a file and look at the console in IE11.

```
<script src="//naver.github.io/egjs-view360/release/latest/dist/PanoViewer/view360.panoviewer.pkgd.min.js"></script>
```

**Comment by WoodNeck** [comment]
Hello, @dansundy! Thanks for reporting the issue.
Looks like the sensor polyfill we're using is not correctly transpiled. I should recheck our env.
I'll notify you when the new version with the fix is released.

**Comment by WoodNeck** [comment]
I've just released a new version(3.3.1) that fixes this issue, please check it :)

![image](https://user-images.githubusercontent.com/26213435/75650511-699efc00-5c99-11ea-9ca6-d20ab94393ba.png)
> IE 11 test

**Comment by dansundy** [comment]
Working for me, thanks! Feel free to close this issue.

Quick question, can I use npm imports but still employ the ES5 transpiled method so that it works in IE11? If so what is the preferred way to do that?

**Comment by WoodNeck** [comment]
View360 offers 3 types of distribution.
If you're using a bundler like rollup or webpack, our imported module will be treated as ES module as we have "module" section defined on our package.json. If so, you have to transpile it yourself with bundler babel plugins.
If you want already transpiled one, you can use node require or module loader like requirejs.
Also, we offer a packaged version with all dependencies. You can grab the file via release or CDN and load that with script tag in the browser. Then, the module will be visible via a global variable `eg.View360.PanoViewer`. Our demo is also built with packaged file :)
