### ISSUE TITLE
Gyroscope motion feature doesn't work on ios phone

### ISSUE THREAD

**Issue by vaibhav1802** [naver/egjs-view360#312]
## Description
I am trying to use this library in my React application. I am not able to initiate motion based gyroscope feature in iphone. I tested in iphone X (ios 13.3). It's working in Android device.
I was expecting that a pop up will show up on the phone when the page is loaded, to ask the user for motion and orientation permission, like it works in your sample code: 
https://naver.github.io/egjs-view360/examples/panoviewer/controls/motion-touch.html
Sample code above, works fine on ios device. 

## Steps to check or reproduce
Here is the code. I am able to load the 360 image and using touch I can move the scene on ios, but not by phone's motion. Not sure what am I missing here to allow the motion sensor.
I checked on Safari and Chrome both.

`export default class App extends Component {
  componentDidMount() {
    const { PanoViewer } = require("@egjs/view360");
    const panoViewer = new PanoViewer(
      document.getElementById("gyroPanoWrapper"),
      {
        image:
          "https://naver.github.io/egjs-view360/examples/panoviewer/controls/equi-car-inside.jpg",
        yaw: 90,
        pitch: -10,
        gyroMode: "yawPitch"
      }
    );
  }

  render() {
    return (
      <div className="App">
        <div class="panoviewer-container viewer">
          <div id="panoSet">
            <div
              style={{
                position: "relative",
                width: "100%",
                height: `1000px`
              }}
              class="panoviewer container"
              id="gyroPanoWrapper"
            ></div>
          </div>
        </div>
      </div>
    );
  }
}`

![IMG_0C715CDDE5DA-1](https://user-images.githubusercontent.com/7563530/79032323-e43c2f00-7be8-11ea-9ecf-31a33d2f71e6.jpeg)

**Comment by WoodNeck** [comment]
Hello @vaibhav1802!
As you said, iOS' device motion is disabled by default.
However, it's not our core feature as that popup heavily relies on other libraries like SweetAlert2.
You have to make a popup yourself. I will give you some sample code :)

> Code from demo (https://github.com/naver/egjs-view360/blob/master/demo/common/js/PanoControls.js#L116)
```js
// For iOS 13+
panoViewer.enableSensor().catch(() => {
    Swal.fire({
        title: "Permission needed! (iOS13+)",
        icon: "question",
        text: "This website needs a permission to access Device motion & Orientation for the immersive experience.",
        showCancelButton: true,
        reverseButtons: true,
        confirmButtonText: "Allow",
        cancelButtonText: "Deny"
    }).then(result => {
        if (result.value) {
            // Granted
            panoViewer.enableSensor().catch(() => {
                Swal.fire(
                    "You've denied a permission!",
                    "You have to completely close out your browser and reconnect this page to enable sensor again!",
                    "error"
                );
            });
        } else if (result.dismiss === Swal.DismissReason.cancel) {
            // User dismissed
        }
    });
});

const iOSVersion = (() => {
    if (/iP(hone|od|ad)/.test(navigator.platform)) {
        // supports iOS 2.0 and later: <http://bit.ly/TJjs1V>
        var v = navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);
        return [parseInt(v[1], 10), parseInt(v[2], 10), parseInt(v[3] || 0, 10)];
    }
})();

// For iOS 12.2 ~ 13
if (iOSVersion && iOSVersion[0] === 12 && iOSVersion[1] >= 2) {
    PanoViewer.isGyroSensorAvailable(available => {
        if (!available) {
            Swal.fire({
                title: "Please enable the Motion Sensor! (iOS12.2~13)",
                icon: "warning",
                text: "This website requires a permission for your device motion sensor for the immersive experience.",
                html: `
                <div style="text-align: left;">
                    <div>
                    1. Open <img src="https://developer.apple.com/design/human-interface-guidelines/ios/images/icons/app_icons/Settings_2x.png" width="20" /> <b>Settings</b>
                    </div>
                    <div>
                    2. Select <img src="https://km.support.apple.com/resources/sites/APPLE/content/live/IMAGES/0/IM26/en_US/safari-240.png" width="20" /> <b>Safari</b>
                    </div>
                    <div>
                    3. Enable <b>Motion & Orientation Access</b>
                    </div>
                    <div>4. Reload the page</div>
                </div>
                `
            });
        }
    });
}
```

You can also check this [live demo](https://codesandbox.io/s/view360-vr-demo-fiqxh)
or, [our wiki page](https://github.com/naver/egjs-view360/wiki/Checklist-for-the-Sensor-and-VR) for detailed implementation :)

**Comment by vaibhav1802** [comment]
Thank you @WoodNeck for sharing this information. It worked. I was expecting that accessing motion sensors will be the part of the library.
