### ISSUE TITLE
Bug semicolon

### ISSUE THREAD

**Issue by AndrewReal0** [naver/egjs-view360#313]
## Description
In the file ~/node_modules/@egjs/view360/declaration/PanoViewer.d.ts
there is a semicolon to spare on line 47.

**Comment by WoodNeck** [comment]
Hello, @AndrewReal0!
Thanks for the report, I'll fix that :)

**Comment by WoodNeck** [comment]
Sorry for the late response.
I've fixed this issue & released 3.3.2 :)
