### ISSUE TITLE
360° Smartphone Panorama shown as 270° Panorama

### ISSUE THREAD

**Issue by HolgerSchulz** [naver/egjs-view360#314]
Hy,

when I load this 360° Smartphone Panorma [(Link to the Picture)](https://www.unser-hueckeswagen.de/static/hueckeswagen/fotos/Rader-Strasse-Wupperbruecke_01_20200505_panorama360_1340x300_bugreport.jpg) it is just shown as a 270° panorama. Continuous scrolling is not possible like on the example picture on [the Smartphone Panorma example page](https://naver.github.io/egjs-view360/examples/panoviewer/projection-type/panorama_image.html).

Why? And how can I change ist?

Thanks
        Holger

**Comment by WoodNeck** [comment]
Hello, @HolgerSchulz!
By its definition, the image should have a width at least six times larger than its height to have 360° panorama enabled. (See [this code](https://github.com/naver/egjs-view360/blob/master/src/PanoViewer/PanoViewer.js#L487))
As your image's height is 300, resizing your image width to 1800 will show 360° panorama with a slight visual defect.
Here's your resized image I've tested & test result.
![resized](https://user-images.githubusercontent.com/26213435/81628900-e63e1b80-943c-11ea-9bfc-382fc2411f2a.jpg)
![image](https://user-images.githubusercontent.com/26213435/81628927-f8b85500-943c-11ea-9e05-314bc0d7dee7.png)

**Comment by HolgerSchulz** [comment]
Hi WoodNeck,
thanks for your fast response!
It would be great if there would be an option to tell if it is a 360° panorama or not - regardless of the resolution.
I would use automatic detection by imageAspectRatio just as a fallback if no explicit definition was made.

Thanks
       Holger

**Comment by WoodNeck** [comment]
Thanks for the suggestion 👍 
I think it's good to have that option.
Like your case, it can be quite confusing without it.
But our panorama renderer can't handle that option at the moment, it'll show space above image aspect as black(clear color).
If you think that's just okay, you can override `yawRange` to 360 at `ready` event with the current version.

Anyway, I'll close this issue for now. Please feel free to reopen whenever it's needed.

**Comment by HolgerSchulz** [comment]
Hi WoodNeck,

I tried this:
panoViewer.on("ready", function() {
  panoViewer.setYawRange([-180, 180]);
});

But then there is a big white gap between (not above) the left and right border of the picture:-(
Any idea to fix it?

Thanks
    Holger

P.S. Do you know an android app like Google Street View to create 360°x180° panoramas, but it doesn't create a panorama picture itself, but exports the taken single pictures to process them in other programs to a panorama picture?
Otherwise it is difficult to take all pictures for a 360°x180° panorama without gaps.
Some software tips to create panoramas would be great!

**Comment by WoodNeck** [comment]
Well like I said, there will be a blank space between the image border.
That can't be handled on the current version, that why our panorama renderer should be updated.
I should work on it later, but I can't guarantee when it will be done.
So for now, I think the best you can do is simply modifying your image like I've done it above.

And, sorry but I don't really much know about Android apps for panorama.

I don't know which image format Google street view uses, but we support lots of projection types like you can see it on https://naver.github.io/egjs-view360/panoviewer.html#projections
So if they use one of our supported formats, I think you can choose that projection type than `panorama` projection type.

For our demo, we've used our 360 camera, so if you can afford it can be an option for you.

**Comment by prudhvinag007** [comment]
> I should work on it later, but I can't guarantee when it will be done.

Hello WoodNeck,

Have you worked on this change yet?
I'm having the same problem, My image width is not 6 times of height, it's actually just 3.5 times of height, i.e., 10141 x 2741
How can I display the image without any white gap with continuous scrolling?

thanks,
