### ISSUE TITLE
Is VR mode customizable?

### ISSUE THREAD

**Issue by Psycholisk** [naver/egjs-view360#315]
## Question
I was wondering, Is it possible to customize the VR mode? 
eg: Adding a navigation menu, hotspots, etc..

**Comment by WoodNeck** [comment]
Hello @Psycholisk!
Unfortunately, as the WebXR spec requires only a canvas element to be shown when enabled, it is impossible for the current version to show a DOM element based hotspot.
So basically, all things should be drawn by WebGL context for the VR mode, which is not supported at the moment. But we'll be working on it though :)
