### ISSUE TITLE
Need help in smartphone panorama

### ISSUE THREAD

**Issue by ramanprtap** [naver/egjs-view360#322]
## Description

Hi I am new on GitHub so please bare with I am using the smartphone panorama with gyro just want to know how can I add the hot spot for that type of image like we are doing for 360

**Comment by WoodNeck** [comment]
Hello, @ramanprtap!
Basically it's totally the same with other projection types, but its pitch range is restricted.
So, just place the hotspots in pitch range and test it to make sure they are shown correctly :)
