### ISSUE TITLE
Anchors are not visible in VR

### ISSUE THREAD

**Issue by Tripl3Design** [naver/egjs-view360#323]
What a great panorama tool! Especially the VR function is impressive.
In the HotSpot example you can load another image by clicking on text in the image.
When I view the example in VR (Oculus Quest and Google Daydream) the anchors are not visible.
Is there a solution for that?

**Comment by WoodNeck** [comment]
Hello @Tripl3Design :)
Yes, it can be done with the [dom-overlay](https://immersive-web.github.io/dom-overlays/) feature of the WebXR API.
But unfortunately, I didn't aware of that feature when I was working on it so it should be updated.
The code should be updated to receive additional features.

dom-overlay feature can be activated like this:
```js
navigator.xr.requestSession("immersive-vr", {
  requiredFeatures: ["dom-overlay"],
  domOverlay: {
    root: ROOT_ELEMENT_TO_YOUR_OVERLAY
  }
})
```
> https://github.com/naver/egjs-view360/blob/master/src/PanoImageRenderer/vr/XRManager.js#L91

We'll work on that soon :)

**Comment by Tripl3Design** [comment]
I hope this feature will be there soon.

**Comment by WoodNeck** [comment]
Hello! Sorry for the late answer.
We've added the option to set a [XRSessionInit](https://developer.mozilla.org/en-US/docs/Web/API/XRSessionInit) value when entering a VR session.

However, I'm afraid to say that won't fix your issue.
I've tested the `dom-overlay` feature that I've mentioned on my Android devices, but looks like it works only with the "immersive-ar" sessions only.
That means the hotspots should be handled with WebGL for now, but our PanoViewer doesn't have any functionality that displays another 3D object on the scene at the moment.
Sorry to say that you should wait for another big update 😢

**Comment by GRA0007** [comment]
Hey @WoodNeck, any chance we'll see this in v4? Would be great to get hotspots showing in VR, potentially their content as well if they have a modal attached.

**Comment by WoodNeck** [comment]
Hello, @GRA0007.
As browsers can't display DOM elements within the "immversive-vr" session at the moment, I guess it's pretty hard to add that feature.
The only alternative that I can think of is to render hotspot UIs with canvas 2D context, which will lack some styling features apparently.
