### ISSUE TITLE
iPad Pro 11" or iPad 9.7" IOS v13.6.1 panorama shakes when gyro enabled

### ISSUE THREAD

**Issue by RobGiffin** [naver/egjs-view360#326]
I've been testing a number of your online panoviewer demos and everything is working well on Chrome/IE 11 on the PC. Also working fine on an iPhone Xs running IOS v13.6.1, but when I tested on two iPad's I own, with any of the demo panorama examples and the gyro enabled the image is shaking badly making it unusable, moving the phone is causing the panorama to move, but it shakes so badly I can't tap on any hotspot.

If I don't enable the gyro (i.e. select 'deny' when prompted to enable gryo) then the 360 panorama works correctly when I scroll around the screen.

Let me know if you need any more info, hopefully it's a simple fix.  Thanks Rob

**Comment by WoodNeck** [comment]
Hello @RobGiffin!
Thanks for reporting. Looks like specs for devicemotion have been changed since iOS 13.4, and it needs to be updated for our component.
We'll work on it soon :)

**Comment by WoodNeck** [comment]
We've released a new version(v3.3.3) fixing this issue.
Check any of our [demos](https://naver.github.io/egjs-view360/panoviewer.html) to see it in its effect :)
