### ISSUE TITLE
Images are blurry in mobile device

### ISSUE THREAD

**Issue by ramanprtap** [naver/egjs-view360#327]
## Description

Image is blurr in mobile device bug
## Steps to check or reproduce

I used eg.view360.PanoViewer.PROJECTION_TYPE.PANORAMA its working fine but the image is blurred in mobile can you please help me. i saw the examples they are also behaving same.

**Comment by WoodNeck** [comment]
Hello, can you show me some examples of it?

**Comment by ramanprtap** [comment]
https://naver.github.io/egjs-view360/examples/panoviewer/projection-type/panorama_image.html 
You can check the above example which is provided by you only when we go to mobile and open it in full view you can see that image is blurring. I have googled for that found that it might me the issue on canvas rendering. Please let me know if you have any suggestion

**Comment by WoodNeck** [comment]
Well, it doesn't look blurry when I checked it on my phone. Can you provide me which OS & browser you're using?
Or, can you show me the panorama image you're using?

**Comment by ramanprtap** [comment]
![21_panaroma_flat](https://user-images.githubusercontent.com/42340762/92471476-9f4b1180-f1f5-11ea-9062-38722f956ba0.jpg)
Please find uploaded image

**Comment by WoodNeck** [comment]
Oh, I see.
Your image has size of 8192 * 1119, which is larger than the 4096 that is the typical maximum texture size from mobile devices.
So, your image is automatically resized to a size smaller than 4096, so your image can be blurry on mobile devices.

Usually, you can resize your image to smaller than 4096 manually to resolve this problem.
Please resize your image to 4096 * 560 and test it again :)

**Comment by ramanprtap** [comment]
can i use different images according to the device ?

**Comment by WoodNeck** [comment]
You don't have to change the hotspot locations :)
Well, we don't provide that feature but at least you can check the maximum texture size like this:
```js
const canvas = document.createElement("canvas");
const gl = canvas.getContext("webgl");
const maxTextureSize = gl.getParameter(gl.MAX_TEXTURE_SIZE);
```
Then use that `maxTextureSize` to choose which image you should show.

**Comment by ramanprtap** [comment]
thanks for your replay I will resize my image and will get back to you. :-)
