### ISSUE TITLE
Hotspots do not adapt to the background images.

### ISSUE THREAD

**Issue by archit1508** [naver/egjs-view360#328]
## Description

When we add a hotspot to the VR world, the image is rendered as static. It does not change perspective with respect to position or angle at all. The hotspot just stays there statically. Please suggest a fix.

**Comment by WoodNeck** [comment]
Hello, @archit1508!
A hotspot is not actually a part of View360 PanoViewer.
It is driven by our demo code which reacts to `viewChange` event.
Please check the actual page source code: https://github.com/naver/egjs-view360/blob/master/demo/examples/panoviewer/etc/hotspot.html#L423
