### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by ramanprtap** [naver/egjs-view360#331]
## Description

Hi Can we control the gyro motion on mobile devices? In mobile it's too fast for android and IOS. Please help.

**Comment by WoodNeck** [comment]
Hello @ramanprtap!
View360's gyro motion is in sync with the actual device rotation.
Like, when you rotate the device 90 degrees, the scenery will also rotate the same 90 degrees.
I'm afraid we don't provide such an option to control the scale of rotation at the moment.
