### ISSUE TITLE
Is it possible lazy loading image with srcset?

### ISSUE THREAD

**Issue by MaximSavin** [naver/egjs-view360#334]
## Description/Question

I have already checked various formats of images, including avif, webp.
But I could not find in the documentation whether it is possible to load images in lazy mode. Something like srcset:
``````
preload-src="poor_me.jpg"
data-src="better_me.jpg"
data-srcset="better_me2x.jpg 400w, better_me.jpg 200w"
``````

**Comment by WoodNeck** [comment]
Hello @MaximSavin!
View360 doesn't provide that option with our API at the moment, but I think you can manually do that.
You can create an empty HTMLImageElement and set the srcset & src to that, then after `load` event use [setImage](https://naver.github.io/egjs-view360/release/latest/doc/eg.view360.PanoViewer.html#setImage) method to apply that responsive image.
We will consider whether to add this feature to the next version :)
Thank you for the suggestion.

**Comment by MaximSavin** [comment]
Wow, cool — good idea! Thanks a lot!
