### ISSUE TITLE
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by Purevsuren46** [naver/egjs-view360#351]
## Description
Sorry guys I am beginner but I don't know how to implement view360 in React.  Please Help Me :))

## Steps to check or reproduce
```jsx
import {PanoViewer} from "@egjs/view360"
(Above useEffect)
const panoViewer = new PanoViewer(document.getElementById("myPanoViewer"),
    {
        image: "https://naver.github.io/egjs-view360/examples/img/equi.jpg"
    }
)
return (
   <div id='myPanoViewer'></div>
)
```

**Comment by WoodNeck** [comment]
Hello, @Purevsuren46!
I think you've initialized View360 before the container element(#myPanoViewer) is created.
Try creating PanoViewer inside `componentDidMount`.
