### ISSUE TITLE
Where is PanoControl or anyAPI to have PieView + FullSize

### ISSUE THREAD

**Issue by mrtk0y** [naver/egjs-view360#352]
## I want PieView and FullMode in the image

Following the Merge request  : https://github.com/naver/egjs-view360/pull/260

![image](https://user-images.githubusercontent.com/37510824/105280811-39c45400-5bdd-11eb-9361-4593ec06253e.png)
![image](https://user-images.githubusercontent.com/37510824/105280816-3d57db00-5bdd-11eb-9b39-51344a6011ff.png)

**Comment by WoodNeck** [comment]
Hello @mrtk0y!
PanoControl is made for our demo so it is not included in our distribution files.
But you can use it by downloading the same code in our `demo` folder.

This also requires other third-party libraries like [screenfull](https://github.com/sindresorhus/screenfull.js/), [SweetAlert2](https://sweetalert2.github.io/), and [webxr-polyfill](https://github.com/immersive-web/webxr-polyfill) so please modify the code in `PanoControl.js` if you don't need these features.

- PanoControl: https://github.com/naver/egjs-view360/blob/master/demo/common/js/PanoControls.js
- PieView: https://github.com/naver/egjs-view360/blob/master/demo/common/js/PieView.js
- initXR: https://github.com/naver/egjs-view360/blob/master/demo/common/js/initXR.js

Applying it:
```html
<head>
    <script src="../../../common/js/PanoControls.js"></script>
    <script src="../../../common/js/PieView.js"></script>
    <script src="../../../common/js/screenfull.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.7.2/dist/sweetalert2.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.min.js"></script>
    <script src="../../../common/js/initXR.js"></script>
</head>

<body>
    <div class="viewer">
        <div class="container"></div>
    </div>
    <script>
    // create PanoViewer with option
    var PanoViewer = eg.view360.PanoViewer;
    var container = document.querySelector(".container");

    var panoViewer = new PanoViewer(container, {
        projectionType: "cubemap",
        image: "../../img/test_cube_3x2_RLUDFB.jpg"
    });

    PanoControls.init(document.querySelector(".viewer"), panoViewer);
    PanoControls.showLoading();
</script>
</body>
</html>
```

**Comment by mrtk0y** [comment]
It's worked! Thanks, bro.
