### ISSUE TITLE
View on my phone, can not use gyro mode

### ISSUE THREAD

**Issue by Seldon1224** [naver/egjs-view360#354]
## Description
I deploy web using egjs  on my computer, and use my phone to view this web, it can open correctly, but it can't use phone's gyro to change view. Did I miss something code? 
## Steps to check or reproduce
Here is html code
`<body>

    <div id="myPanoViewer"></div>
    <script src="../public/js/PanoViewer/view360.panoviewer.pkgd.min.js"></script>
    <script>
        // create PanoViewer with option
        var PanoViewer = eg.view360.PanoViewer;
        var container = document.getElementById("myPanoViewer");// Area where the image will be displayed(HTMLElement)

        var panoViewer = new PanoViewer(container, {
            // If projectionType is not specified, the default is "equirectangular".
            image: "../public/img/imgRoom3.jpg", // Specifies an image of the "equirectangular" type.
            gyroMode: "yawPitch"
        }
        );
        panoViewer.setGyroMode("yawPitch");
    </script>

</body>`

**Comment by Seldon1224** [comment]
when I view demo on https://naver.github.io/egjs-view360/examples/panoviewer/etc/hotspot.html， the gyro on my phone works.

**Comment by WoodNeck** [comment]
Hello @Seldon1224! Can you tell me which mobile phone OS you're using?
If it's iOS, you can refer to these pages
- https://github.com/naver/egjs-view360/wiki/Checklist-for-the-Sensor-and-VR
- https://github.com/naver/egjs-view360/blob/master/demo/common/js/PanoControls.js#L117

**Comment by Seldon1224** [comment]
Thanks for your reply，I'm using Android phone. And It's seem that I miss something code, maybe..

**Comment by WoodNeck** [comment]
Oh, then I guess you're not using an HTTPS server.
You have to provide the page via an Encrypted HTTPS connection in order to access the Device Orientation API.

**Comment by Seldon1224** [comment]
Okay,I will enable https server to test, thanks for your help.

**Comment by WoodNeck** [comment]
Good! I'll close this issue then, feel free to reopen it when it's not resolved.
