### ISSUE TITLE
isGyroSensorAvailable returns false after permission given - iOS

### ISSUE THREAD

**Issue by thecuriouspixel** [naver/egjs-view360#356]
## Description
Using enableSensor() works to catch permission not given - but is ambiguous when permission is given.

On a computer's browser enableSensor() returns with no error, as it does on iOS. So to check if I ACTUALLY have sensor information, I tried calling isGyroSensorAvailable one more time. Even when permission is granted - isGyroSensorAvailable returns false. Reloading the page shows it to be true - but was hoping to update state without a reload.

Is there a better way to see if the device we are on has gyro capability? If so, I can then assume no error from enableSensor means I have access to it - or is there a better way to get updated capability after trying to enable it?

## Steps to check or reproduce
`panoObject?.enableSensor().then(() => {`
          `console.log("enable returned with no error");`
          `PanoViewer.isGyroSensorAvailable((isAvailable) => {`
            `console.log(isAvailable);`
`// still false`
          `});`
       ` })`
        `.catch((reason: string) => {`
          `console.log(reason);`
       ` });`

**Comment by WoodNeck** [comment]
Hello, @thecuriouspixel!
I think that if the `isGyroSensorAvailable` returns false before reloading the page, that should be regarded as a bug.
I'll test and fix that if it really works as you've mentioned.

The methods should work like this:
|Env|enableSensor|isGyroSensorAvailable|
|---|:---:|:---:|
|Desktop|true|false|
|Mobile-Android|true|Whether the "devicemotion" is working|
|Mobile-iOS|Depends on user permission|Whether the "devicemotion" is working|

As the desktop also returns `true` in the `enableSensor`, that shouldn't be the way to check the gyro availability.

So, the basic way to enable the sensor then check the gyro availability is: 
```js
const viewer = new PanoViewer(el, options);

/**
 * @returns Promise<boolean>
 */
const checkGyroAvailability = async () => {
  try {
    await viewer.enableSensor();
    return new Promise((resolve) => {
      PanoViewer.isGyroSensorAvailable(resolve);
    });
  } catch (e) {
    // Failed to retrieve the user permission
    return false;
  }
}
```
> (Above code is almost same as yours)

I'll test the above code works correctly in the iOS :)

**Comment by WoodNeck** [comment]
@thecuriouspixel 
I've tested with the above code, and it returns `true` after getting the user permission prompt.
Test env was iPad(14.4.2) on Safari, can you share which env/actual code you're using?

**Comment by thecuriouspixel** [comment]
Very strange. I'm using the exact code I posted. Here is exactly what is there now - and I still get false after giving permission and the gyro is functioning.

```
console.log(`Try to enable sensor`);
      panoObject
        ?.enableSensor()
        .then(() => {
          console.log("enable returned with no error");
          PanoViewer.isGyroSensorAvailable((isAvailable) => {
            console.log(`second is available check ${isAvailable}`);
            // still false
          });
        })
        .catch((reason: string) => {
          console.log(`rejected for reason ${reason}`);
        });
```

and I see this:
```
[Log] GyroAvailable false (main.chunk.js, line 937)
[Log] Try to enable sensor (main.chunk.js, line 902)
[Log] enable returned with no error (main.chunk.js, line 904)
[Log] second is available check false (main.chunk.js, line 914)
```

**Comment by WoodNeck** [comment]
I've just tested with exact same code as yours, but I couldn't test on the iPhone as I don't have one now
![image](https://user-images.githubusercontent.com/26213435/115006150-815c3280-9ee3-11eb-8278-75d58c3e18ec.png)
Result was the same, it returns `true`
Are you using the latest version of Panoviewer? I've tested it on v3.4.3.

**Comment by thecuriouspixel** [comment]
I am on 3.4.3. I just tried an iPad, and I also still only see "false" after giving permission. How odd. I'll ask some colleges that are better at React than I am to make sure I'm not doing something dumb. I'll report back.

**Comment by WoodNeck** [comment]
Please report to me if there's no progress after. I can debug that for you.
Actually we're planning on making the framework version of the View360, so it can be very helpful to us if it's a framework-specific issue.

**Comment by thecuriouspixel** [comment]
We found "the issue" and you might want to decide how you feel about it.
What was NOT in my test sample code to you was the fact that elsewhere I had already checked for isGyroAvailable. The reason I do this is to let people know we are about to ask for a permission. Because the initial check was "false" since the gyro had not been enabled yet, your code seems to cache it with a constant after that first check.

So if you:
• Check isGyroSensorAvailable and it is false
• Then, enableSensor and give it permission
• Check isGyroSensorAvailable will always be false

I think it's important to be able to query this method more than once - as we've seen people are more likely to give permission to things if you warn them in advance that you are going to do it. But, we don't want to annoy people that have already given us permission.

**Comment by WoodNeck** [comment]
Sorry for the late answer!
I know this can be confusing, so I'm finding a way to make this more easy to use.

As the `enableSensor` returns false on init(without user interaction) only on the iOS where gyro is not enabled,
you can use this behavior to check whether the gyro is enabled on iOS.

You can check our wiki: https://github.com/naver/egjs-view360/wiki/Checklist-for-the-Sensor-and-VR#ios13
and demo: https://codesandbox.io/s/view360-vr-demo-fiqxh?file=/src/index.js

for actual implementation.
