### ISSUE TITLE
Cubestrip coordinates slightly inaccurate

### ISSUE THREAD

**Issue by webciter** [naver/egjs-view360#357]
Tested the EAC Format for cubemaps but the video has gaps in the join of the cube. Maybe it needs altering slightly.

**Comment by WoodNeck** [comment]
Hello, @webciter!
![naver github io_egjs-view360_examples_panoviewer_projection-type_youtube html](https://user-images.githubusercontent.com/26213435/115190573-32044500-a123-11eb-9701-301f3eae97dd.png)

The above screenshot is captured in our [demo](https://naver.github.io/egjs-view360/examples/panoviewer/projection-type/youtube.html), is that the same issue?
I'll take a look at that.

**Comment by webciter** [comment]
yes that is the issue, i was thinking maybe the vertices should overlap, then maybe push the uvs back a little

**Comment by WoodNeck** [comment]
Okay, I'll check this issue.
I'll leave a comment here after it's fixed :)

**Comment by WoodNeck** [comment]
@webciter 
We've just released v3.5.0 that fixes this issue.
You can try setting `cubemapConfig.trim` option to remove those graphical glitches between texture tiles.
I've also removed the above glitch in our [demo](https://naver.github.io/egjs-view360/examples/panoviewer/projection-type/youtube.html) :)

**Comment by webciter** [comment]
thanks works ok now.
