### ISSUE TITLE
Hotspot moving when data-pitch not 0

### ISSUE THREAD

**Issue by ipermediastudio** [naver/egjs-view360#365]
When setting the hotspot position, if the parameter data-pitch is pointing at the bottom, or top of the 360 image/video, when you move the camera left and right, the hotspot is not maintaining the position.
The more data-pitch parameter differ from 0, the more the element is moving when you rotate the camera left and right.

In the example the data-pitch is "-70".
Example:
https://codepen.io/erik-c/pen/vYZjYqq

**Comment by WoodNeck** [comment]
Hello @ipermediastudio!
Actually, I'm sorry to say but that's not our official feature but only for the demo.
We're planning to add it as our official feature, with the big update of PanoViewer.
I didn't write that code so I don't know everything about it, but I think it should be updated with the part where it calculates hotspot position to use the camera matrix.
