### ISSUE TITLE
Panoviewer is not working on Safari 15

### ISSUE THREAD

**Issue by WoodNeck** [naver/egjs-view360#366]
## Description
Due to the `xrCompatible` property when creating WebGL context, PanoViewer is not working on Desktop Safari 15

**Comment by checkthemethod** [comment]
@WoodNeck just noticed this fix for iOS15, did you also notice any of this behavior in your testing? I just logged this bug: https://github.com/naver/egjs-view360/issues/369

**Comment by WoodNeck** [comment]
@checkthemethod Hello! I think this issue is identical to yours.
The reason for being unable in iOS15 is caused by the one property when creating the WebGL context, which is `xrCompatible`
I've removed that in #367, and it will be released right in the next version :)

**Comment by checkthemethod** [comment]
@WoodNeck thank you for the quick reply. Is there an expectation or timeline on releasing the next version? Would love to test it out.

**Comment by WoodNeck** [comment]
As soon as the reviews are finished! I hope to release in the next week.
