### ISSUE TITLE
A certain video does not load / play on an iPad

### ISSUE THREAD

**Issue by lukef0** [naver/egjs-view360#370]
## Description

Basic situation:
The final website should show a VR video in the header area.
The visitor can move around in the 3D space.
 
Problem: 
the VR video loads on all devices except on a friend's iPad (hardware version unknown, latest iPad OS version).
On the other hand, other iPads (e.g. iPad Pro 2019 12.9 inch) load the video without any problems.
I attached a video of the unexpected behaviour.
 
My thoughts / approaches:
Initially I suspected an incompatibility of iPadOS and PanoView, but this was quickly ruled out after successfully loading the demo version of the engine on the iPad and compatibility should exist according to the GitHub compatibility table.
After the demo version was fully functional, I developed the programming from scratch. (I took extra care to use the latest files).
Again, this did not result in any improvement.
The final approach was to take the demo version and modify the source code step by step - each step was tested on the iPad for functionality. 
It turned out that any mp4 video worked, only the correct and desired video did not.
 
This leads me to the conclusion that something is wrong with the video. This was then re-exported by the producer - nothing changed. Slowly I do not know what else the error could be.

## Steps to check or reproduce

For testing I used the demo "Video Tag (Equirectangular)". Nothing was changed in the code except for the video source. Various mp4 videos worked without any problems, only the "right" version did not.

https://user-images.githubusercontent.com/92399155/137019496-c8036da4-a7a0-4433-b5e6-1ac5c19d621a.MP4

.

**Comment by WoodNeck** [comment]
Hello @lukef0!
Is it possible for me to check the video?
I guess it's either the video's problem or the iPad of your friend's.

Or if you can't, you can try those:

1. Check the video is loadable / playable just using the \<video\> tag alone.
Simple, if the video is not play or loadable itself, PanoViewer can't show it on the canvas.

2. Create a WebGL rendering context with a canvas, and check whether you can use the video as the canvas.
This is the process of PanoViewer to show an image on it. Some types of video are not showable if it is used as texture while it can play via the \<video\> tag alone (like #355)
If that's too burdensome, try other tools that can make things easier like three.js that can use video as a texture.
- https://threejs.org/docs/#api/en/textures/VideoTexture

3. If both works, maybe it's the issue of our inner module that even though the video was loaded, it doesn't consider it as loaded.
Check our inner module([@egjs/imready](https://naver.github.io/egjs-imready/)) triggers ready event with that video.

**Comment by lukef0** [comment]
Hello @WoodNeck 
thank you very much for your quick response.
I can provide the video, that's no problem, you can access it at https://improvr.de/wp-content/vr_video/improvr-okt.mp4.
In the meantime, I will have a look at the other two approaches of yours.

**Comment by WoodNeck** [comment]
@lukef0 
I've just checked your video and found out that the size of it is 4096 * 2048.
In older iPad, the maximum texture size we can use is up to 2048 so I think that is the cause.
You can check it by calling the `gl.getParameter(gl.MAX_TEXTURE_SIZE)` to get the maximum texture size available.
So, you can try serving the multiple videos, and choose one of them by the result of the query.

Check those links:
- #304 
- https://stackoverflow.com/questions/2505186/what-is-the-maximum-texture-size-available-on-the-ipad

**Comment by lukef0** [comment]
Thank you very much, that was exactly the solving clue! I have now added an if statement and based on that the larger or smaller video is loaded (so exactly as recommended)
