### ISSUE TITLE
Export missing for @egjs/vue3-view360

### ISSUE THREAD

**Issue by si7o** [naver/egjs-view360#376]
## Description
I recently tried to use @egjs/vue3-view360 to display an equirectangular panorama and found out that, after installing the latest version and running my vue3 application, it returns a console warning saying a couple exports are missing on ´@egjs/view360´:
- getValidProps
- generateCanvasKey

## Steps to check or reproduce
Once `@egjs/vue3-view360` is installed, run `npm run serve` to start your vue application and you should get the following warnings:

```bash
 warning  in ./node_modules/@egjs/vue3-view360/dist/view360.esm.js
"export 'generateCanvasKey' was not found in '@egjs/view360'
 warning  in ./node_modules/@egjs/vue3-view360/dist/view360.esm.js
"export 'getValidProps' was not found in '@egjs/view360'
 warning  in (webpack)/buildin/global.js
```

I also navigated to the node_modules egjs files and found this on `.\node_modules\@egjs\vue3-view360\src\PanoViewer.ts`:
![imagen](https://user-images.githubusercontent.com/5405326/145382675-50453bed-daea-47a9-8456-67186dd5dd9d.png)

**Comment by WoodNeck** [comment]
Hello @si7o!
It looks like there was a mistake setting the correct dependency version in vue3-view360.
I've just updated its version to 3.0.1 to fix this issue, please try that :)

**Comment by si7o** [comment]
It works now. Thank you for fixing it so fast :)
