### ISSUE TITLE
Vue3 + Vite Image dissappears once clicked and no errors in console 

### ISSUE THREAD

**Issue by masterofshapes** [naver/egjs-view360#377]
Installed the vue3 package globally using example. Pass image path and when I click on image on screen it immediately disappears with no errors in console.

![image](https://user-images.githubusercontent.com/4534991/145664716-2e84cdf3-796c-4e2b-844f-069ca5d13c35.png)

![image](https://user-images.githubusercontent.com/4534991/145664733-1e084062-2489-497f-9ff3-2c9baf823c1e.png)

![image](https://user-images.githubusercontent.com/4534991/145664737-3bfe1283-6e51-4200-b5ce-f50b17e85aa9.png)

**Comment by WoodNeck** [comment]
Hello @masterofshapes!
This is probably due to the CSS issue, that the wrapper size becomes 0.
Please add some style CSS to your wrapper, like this:
```vue
<PanoViewer
  :image="'https://naver.github.io/egjs-view360/examples/img/equi.jpg'"
  :style="{ position: relative, height: '400px' }" />
```
