### ISSUE TITLE
Not working on iOS 

### ISSUE THREAD

**Issue by juancarlosjr97** [naver/egjs-view360#378]
## Description
The latest code is not working on iOS. Tested on the following devices:

* iPhone 8 - iOS 15.2
* iPhone Xs Max - iOS 15.2

## Steps to check or reproduce

1. Open the site https://naver.github.io/egjs-view360/examples/panoviewer/etc/videojs.html on an iPhone running the latest version of iOS (v15)
2. Accept the motion and control request
3. The video player is stuck with the 360 icon and the video does not start

**Comment by WoodNeck** [comment]
Hello @juancarlosjr97!
I've tested it on my iPadOS 15.2 & some other environments(Windows, Android) and looks like it works fine.
Can you tell me which browser did you tested? I want to know whether this is an iOS-specific issue :)

**Comment by juancarlosjr97** [comment]
Sure :) 

I have tested on:

* iPhone 8 - iOS 15.2 - Safari, Chrome and Firefox
* iPhone Xs Max - iOS 15.2 - Safari (I do not have access to it right now)

Also managed to reproduce the error using my mac

* Macbook Air - macOS Monterrey - Google Chrome (Dev Tools - Selecting iOS Device emulator) - Version 96.0.4664.110 (Official Build) (arm64) - iPhone 6/7/8 Plus DevTools Emulator with Device Mode
* * Macbook Air - macOS Monterrey - Google Chrome (Dev Tools - Selecting iOS Device emulator) - Version 96.0.4664.110 (Official Build) (arm64) - iPad Pro DevTools Emulator with Device Mode
* Xcode Emulator - iOS 15.1 - iPhone X - Safari

I have tested on the browser selecting other devices such as Android - Pixel 2 XL and Moto G4 and appears to be working fine, and mainly is an iOS issue.

Thank you for checking @WoodNeck!

**Comment by WoodNeck** [comment]
@juancarlosjr97
Thanks for the detailed response!
Fortunately, I can test some of them myself. I'll check the cause asap :)

**Comment by WoodNeck** [comment]
Well, the fix was super simple.
- https://github.com/naver/egjs-view360/pull/379

Looks like videojs manipulates the video element on initialization, and that was the cause.

**Comment by juancarlosjr97** [comment]
YEAH! Awesome @WoodNeck :)
