### ISSUE TITLE
How to use with Video.js and Vue?

### ISSUE THREAD

**Issue by camhart** [naver/egjs-view360#380]
I'm struggling to get this to work alongside videojs and vue.  Here's what I've got so far:

```
<template>
  <div ref="videoParentContainer">
    <div ref="panoViewer">pano viewer!</div>
    <video ref="videoElement" class="video-js" controls width="650px" height="325px">
      <source :src="s" />
    </video>
  </div>
</template>

<script>
import 'video.js/dist/video-js.min.css';
import 'video.js/dist/video.min.js';
import videojs from 'video.js'

import { PanoViewer } from "@egjs/vue-view360";

export default {
  name: "VideoPlayer",
  components: {
    // eslint-disable-next-line vue/no-unused-components
    PanoViewer
  },
  props: {
    s: {
      type: String,
      required: true
    },
    t: {
      type: String,
      required: true
    }
  },
  data() {
    return {
      panoViewer: null
    }
  },
  methods: {
    setupVideoPlayer() {
      const self = this
      // eslint-disable-next-line no-unused-vars
      const player = videojs(this.$refs.videoElement, {

      }, function() {
        self.onReady(this)
      })

      // player.on() //event listener
    },
    onResize(event) {
      console.log(`onResize ${JSON.stringify(event, null, 2)}`)
      if(this.panoViewer) {
        this.panoViewer.updateViewportDimensions()
      }
    },
    onPlay(event) {
      console.log(`onPlay ${JSON.stringify(event, null, 2)}`)
    },
    buildPanoViewer() {
      this.panoViewer = new PanoViewer(this.$refs.videoElement, {
        video: this.$refs.videoElement,
        projectionType: 'equirectangular',
        useZoom: false
      })
      // this.$refs.videoElement.style.visibility = 'hidden' //hide the original element
      // this.$refs.videoElement.style.display = 'none' //hide the original element

      this.panoViewer.$mount(this.$refs.panoViewer)
    },
    onReady(player) {
      console.log(`onReady ${JSON.stringify(player, null, 2)}\n${JSON.stringify(event, null, 2)}`)
      this.buildPanoViewer()
    },
  },
  mounted() {
    this.setupVideoPlayer()
    window.addEventListener('resize', this.onResize)
  },
  beforeDestroy() {
    window.removeEventListener('resize', this.onResize)
    if(this.panoViewer) {
      this.panoViewer.$destroy()
      this.panoViewer = null
    }
  }
}
</script>

<style scoped>

</style>
```

I can see the video.js element.  If I uncomment the display = 'none' it goes black.  I can tell that the PanoViewer does get mounted because the text goes away.  But it's not working correctly.

**Comment by WoodNeck** [comment]
Hello @camhart!
I didn't check the actual page so I'm not sure but I think a common cause for this issue is canvas CSS that the canvas isn't displayed at all.
Check whether your canvas is correctly displayed, which should have a width/height greater than 0.
Or, check whether the canvas is hidden behind the video wrapper.

The following snippet is a working code that I've tested on my local env.

```vue
<template>
  <div id="wrapper">
    <pano-viewer
      ref="pano"
      :projectionType="'equirectangular'"
      :useZoom="false"
    >
      <video ref="videoElement" class="video-js" controls width="650px" height="325px">
        <source src="../static/seven.mp4" />
      </video>
    </pano-viewer>
  </div>
</template>
<script lang="ts">
import Vue from "vue";
import 'video.js/dist/video-js.min.css';
import 'video.js/dist/video.min.js';
import videojs from 'video.js'

export default Vue.extend({
  mounted() {
    const player = videojs(this.$refs.videoElement, {}, this.onReady);
  },
  methods: {
    onReady() {
      this.$refs.videoElement.style.display = 'none' //hide the original element

      this.$refs.pano.setVideo(this.$refs.videoElement);
    }
  }
})
</script>
<style>
#wrapper {
  display: inline-flex;
  position: relative;
}

.view360-canvas {
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
  z-index: 1;
}
</style>
```

**Comment by camhart** [comment]
That certainly looks cleaner than what I was doing.  I've made the updates--now I get a black box with no video playing.  Canvas is only a portion of the video.

![image](https://user-images.githubusercontent.com/3038809/148368621-867a608e-e7b7-4d38-99ab-371755955d53.png)

**Comment by WoodNeck** [comment]
That looks like the CSS is not applied due to your `<style>` being `scoped`, try removing that (and fix it later).

The video's at here :)
- https://naver.github.io/egjs-view360/examples/panoviewer/etc/img/seven.mp4

**Comment by camhart** [comment]
Okay, now when the video loads its all black with no play button or controls.
![image](https://user-images.githubusercontent.com/3038809/148370028-c564197e-038d-4304-99ad-c895285bfa0c.png)


If I temporarily remove the z-index from canvas, the play button is visible.
![image](https://user-images.githubusercontent.com/3038809/148370072-fa6d725d-d4db-486a-b1ba-c02621ede485.png)

I can click it, then restore the z-index and I see the video appears to be working though is perhaps zoomed in a bit.
![image](https://user-images.githubusercontent.com/3038809/148370132-e8cb1a43-600f-4868-ab0b-660eac347a7f.png)

**Comment by WoodNeck** [comment]
I found out that the canvas hides the control buttons, I think we should remove the `z-index` that I've added on the style of the `view360-canvas`. 

```diff
.view360-canvas {
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
- z-index: 1;
}

+.video-js {
+  background: transparent !important;
+}
```

**Comment by camhart** [comment]
That did the trick the video is playing.  But now:

1. There are no pano buttons/controls
2. The video is zoomed in quite a bit by default

I assume I could fix #2 by setting zoom manually, though should it be zoomed in on me by default?  And are the pano buttons showing for you because they don't for me.
![image](https://user-images.githubusercontent.com/3038809/148371177-411141ea-06cd-411d-b0ad-eb3d8463d9f4.png)

**Comment by WoodNeck** [comment]
I think the zoom you say is directly connected with the `fov` value, which you can modify also.
`45` would be fine for you I guess, but you can lower the value if it's not zoomed enough.

Also, sorry to say but we don't offer that buttons/controls officially, like bundled with other packages.
That buttons are from here: https://github.com/naver/egjs-view360/blob/master/demo/common/js/PanoControls.js
and can be initialized like this:

```js
// Code grabbed from: https://naver.github.io/egjs-view360/examples/panoviewer/etc/hotspot.html

var panoviewer = document.querySelector(".viewer");
// "viewer" is an instance of PanoViewer
PanoControls.init(panoviewer, viewer);
PanoControls.showLoading();
```

**Comment by camhart** [comment]
You've been incredibly helpful.  Thank you.

How do I access the PanoViewer API when using the PanoViewer vue component?

**Comment by WoodNeck** [comment]
I'm happy to help you :)
It's identical to the original [PanoViewer API](https://naver.github.io/egjs-view360/release/latest/doc/).
The only difference is listening events, that you can use `v-on`(or @) to add event handlers.

**Comment by camhart** [comment]
Awesome, thanks for that.

I just tested this on an iPhone--for some reason the iphone seems to force you to view videos in full screen, but shows it not in VR/360 mode.  However when I try the demo at https://naver.github.io/egjs-view360/examples/panoviewer/etc/videojs.html, it works correctly as long as I don't click video.js's fullscreen button.  Any ideas?

**Comment by WoodNeck** [comment]
Well, I'm not sure about this but maybe the click event is propagated to the fullscreen button for whatever reason?

**Comment by camhart** [comment]
I'll keep digging, thank you!

**Comment by camhart** [comment]
Sorry, back at it.  I've realized the video wasn't being zoomed, but the view360-canvas class skews the canvas object.

```
.view360-canvas {
  width: 100%;
  height: 100%;
}
```

I'll try to play around with what's causing it, but if you have any ideas it'd be helpful.

**Comment by camhart** [comment]
Setting the width/height on the PanoViewer instead of the video fixed it.
```
      <pano-viewer
          ref="pano"
          style="width: 800px; height: 480px;"
      >
       <video ref="videoElement" class="video-js"  playsinline>
```
