### ISSUE TITLE
Hotspots in 360 video ?

### ISSUE THREAD

**Issue by PaulKsi** [naver/egjs-view360#383]
Hello, is it possible to put a hotspot in 360 video? Thank you.

**Comment by WoodNeck** [comment]
Hello @PaulKsi!
Although we have a demo of it, it is not officially provided.
See https://github.com/naver/egjs-view360/blob/master/demo/examples/panoviewer/etc/hotspot.html#L296

**Comment by PaulKsi** [comment]
the demo provided is photo? i am interested in video hotspots? Thank you!

**Comment by WoodNeck** [comment]
Oh, I didn't see the word "video", it is not supported at the moment.
Anyway, is there any specific format for it? Like, how anchors should move around timeline?
