### ISSUE TITLE
Egjs-view360 not working when image has width > 4096px

### ISSUE THREAD

**Issue by huynhpg** [naver/egjs-view360#384]
Egjs-view360 not working with when use image with high quality (width >= 8096px) or bigger size. It show only black image on mobile chrome

**Comment by WoodNeck** [comment]
Hello @huynhpg!
WebGL typically doesn't support highres textures bigger than 4096px in mobile devices.
In some iOS devices, this even lowers to 2048px.

You can check the available maximum size of the texture like this:
```js
const canvas = document.createElement("canvas");
const gl = canvas.getContext("webgl");
const maxTextureSize = gl.getParameter(gl.MAX_TEXTURE_SIZE);
```

**Comment by ToWipf** [comment]
Is there a way to bypass or increase the MAX_TEXTURE_SIZE?
