### ISSUE TITLE
[Feature request] Built-in autoCruising options

### ISSUE THREAD

**Issue by mjau-mjau** [naver/egjs-view360#385]
I came across egjs-view360, and it looks very promising! In addition to #381 the only missing feature is built-in auto-rotate (autoCruise) options. You already have an example [custom-control.html](https://naver.github.io/egjs-view360/examples/panoviewer/controls/custom-control.html) using custom functions, but it's not optimal.

1. Users should be able to drag/swipe also view is auto-rotating.
2. Auto-rotate should pause on user-interaction and be able to resume after user inactivity timeout.
3. It would be useful if this functionality was built-in, `autoRotate` `autoRotateIdleDelay`.

Thanks. I just wanted to post some feedback as I was researching several Panorama viewers, and egjs-view360 looks like one of the most promising allround solutions ⭐️

**Comment by WoodNeck** [comment]
Hello @mjau-mjau! Thanks for the suggestion!
I'm sure we have to add that feature. We're preparing for the next major version of this component so I think it will be added then.
I'm working on another project at the moment so it might take a while though.

Take a look at this another component of our team, it has an option named `autoplay` with exact same feature.
I think if the feature is made in View360, it might look just like this :)
- https://naver.github.io/egjs-view3d/docs/options/control/autoplay

**Comment by mjau-mjau** [comment]
> Take a look at this another component of our team, it has an option named `autoplay` with exact same feature. I think if the feature is made in View360, it might look just like this :)
> 
> * https://naver.github.io/egjs-view3d/docs/options/control/autoplay

👍🏼 Indeed. Thanks.

**Comment by WoodNeck** [comment]
`autoplay` is added in the new major version (`v4`), please try that!
- https://naver.github.io/egjs-view360/docs/options/miscellaneous/autoplay
