### ISSUE TITLE
Frontend hotpost creating !!!

### ISSUE THREAD

**Issue by Piniteinfo1** [naver/egjs-view360#389]
## Description

Hi, I am trying to create a hotspot from front end!!! Suppose a user wants to add a hotspot anywhere on the 360 images, he should be able to create or delete and link the image with another 360 images !!!

**Comment by WoodNeck** [comment]
Hello @Piniteinfo1!
It is not supported as an official feature at the moment, please check issue #289

**Comment by WoodNeck** [comment]
Hotspot is now an official feature in the new major version (`v4`).
- https://naver.github.io/egjs-view360/docs/hotspot
