### ISSUE TITLE
Is it possible drag hotspot.

### ISSUE THREAD

**Issue by ChanderShekharKestone** [naver/egjs-view360#390]
Is it possible drag hotspot from point a to point b.
And after reached point b get yaw and pitch.

**Comment by ChanderShekharKestone** [comment]
Ok, thanks for reply.
How to get yaw and pitch on mouseclick.

**Comment by WoodNeck** [comment]
@ChanderShekharKestone 
You need some math for that feature.
Check this demo: https://codepen.io/woodneck/pen/LYdGGXo

**Comment by ChanderShekharKestone** [comment]
Thank you so much.

**Comment by ChanderShekharKestone** [comment]
Hi
Hotspot position not remian at same point. 
If drag hotspot lost position from it defined position.
In below link.
https://naver.github.io/egjs-view360/examples/panoviewer/etc/hotspot.html

How i fixed it if drag hotspot not lose it's defined position.

**Comment by WoodNeck** [comment]
@ChanderShekharKestone
As It's not an official feature, I can't help you further as I have to check your whole code for this.

Please check whether the calculation logic is correct. Save the hotspot position as a 3-dimension point and project its position to screen using yaw, pitch, and fov value.

**Comment by ChanderShekharKestone** [comment]
This is a  demo [link](https://codesandbox.io/s/f4snyc) see here when you drag hotspot position not remian same.
If you have any working example please share it will be very helpful. 
https://codesandbox.io/s/f4snyc

**Comment by WoodNeck** [comment]
@ChanderShekharKestone 

Please check this comment:
- https://github.com/naver/egjs-view360/issues/310#issuecomment-604378183

**Comment by ChanderShekharKestone** [comment]
Thank you so much.

**Comment by ChanderShekharKestone** [comment]
https://github.com/naver/egjs-view360/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted

**Comment by ChanderShekharKestone** [comment]
I tried that code also not working for me. Hotspot position not fixed at same point.

**Comment by ChanderShekharKestone** [comment]
> tspot position not fixed at same

Is there anyone who have solution to fixed hotspot position.

**Comment by WoodNeck** [comment]
Hotspot is now an official feature in the new major version (`v4`).
I also fixed this position issue in the new version.
- https://naver.github.io/egjs-view360/docs/hotspot
