### ISSUE TITLE
React: Controls plugin is broken

### ISSUE THREAD

**Issue by GRA0007** [naver/egjs-view360#406]
## Description

The Controls plugin in React renders two pie view elements, one of them is non-functional and very large. It also renders all the buttons even if not applicable to the platform, but they are missing icons.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/8862273/224232508-409355aa-74cf-4255-8b8a-31384673999a.png">

## Steps to check or reproduce

- Using version 4.0.0-beta.4 of the React version
- Simple example with Controls plugin

Codesandbox demo: https://codesandbox.io/s/egjs-view360-react-controls-q1u9cr

**Comment by WoodNeck** [comment]
@GRA0007 
Hello, looks like this is a bug with React's StrictMode.
I guess the plugins are not destroyed properly on unmount, I'll take a look at it.

**Comment by WoodNeck** [comment]
Fixed in 4.0.0-beta.5
