### ISSUE TITLE
Not working in next js

### ISSUE THREAD

**Issue by tarifalhasan** [naver/egjs-view360#409]
## Description
Not working in next js

**Comment by WoodNeck** [comment]
Hello, @tarifalhasan. Thanks for reporting the issue.

I found out that our projection classes are `undefined` in SSR when imported.
So that the `TypeError: _egjs_react_view360__WEBPACK_IMPORTED_MODULE_7__.EquirectProjection is not a constructor` error is triggered.

I'll check this issue, but meanwhile, you can try the following method to bypass this issue:
```js
import View360, { EquirectProjection } from "@egjs/react-view360";

export default () => {
  const projection = React.useMemo(() => {
    // or directly, "if (EquirectProjection)" also works.
    if (process.browser) {
      // only on client-side
      return new EquirectProjection({ src: "https://iili.io/HGJXAqN.jpg" });
    } else {
      return null;
    }
  });

  return (
    <View360 projection={projection}></View360>
  );
}
```

If it's not the case, please let me know more details about the issue and I'll take a look at it.

**Comment by tarifalhasan** [comment]
Still face error

**Comment by tarifalhasan** [comment]
please give me complete guide how can use this package. i really like this package this is awesome

**Comment by tarifalhasan** [comment]
![error](https://user-images.githubusercontent.com/92237522/226909463-ac363c45-a8c8-40a9-b7b1-78be5d3ae763.PNG)

**Comment by WoodNeck** [comment]
Glad you like the project, check out this [codesandbox demo](https://codesandbox.io/p/sandbox/adoring-cookies-ouly8o?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A16%7D%5D).

**Comment by tarifalhasan** [comment]
Thanks this now work but i face i more bugs imported image not working

**Comment by tarifalhasan** [comment]
![Capture222](https://user-images.githubusercontent.com/92237522/227094905-b5a67b78-f16b-4933-a518-b3b14c9fabb3.PNG)
![lasterror](https://user-images.githubusercontent.com/92237522/227094912-dad8e8d7-4cfe-451b-a36d-4a744a388bb1.png)

**Comment by WoodNeck** [comment]
I guess the `image2` is not in the correct type that `Projection` requires, what is the actual value of it?
`src` of `Projection` should be in string.

**Comment by tarifalhasan** [comment]
image 2 working in normally

**Comment by WoodNeck** [comment]
Images loaded with `import` in next.js looks like this:
![image](https://user-images.githubusercontent.com/26213435/227429231-70134a9f-4764-4e22-98ba-16e4c271215c.png)

What View360 needs is `src` string in that object.

Change this:
```ts
return new EquirectProjection(img2);
```

To this:
```ts
return new EquirectProjection(img2.src);
```

and it'll work

**Comment by tarifalhasan** [comment]
Thanks
