### ISSUE TITLE
React View360 component not showing gyro abilities

### ISSUE THREAD

**Issue by Helyios** [naver/egjs-view360#412]
## Description
I am trying to recreate the 360View from the demo website which shows an icon to use the gyroscope of my iPhone.

I am using the latest version of create react app (react 18.2.0) and the latest egjs/react-view360 (4.0.0-beta.5).

## Steps to check or reproduce
I just created a react app and replaced everything inside the App.js component. 

Here is the code inside App.js

```
import React, { useMemo } from "react";
import View360, {
  ControlBar,
  EquirectProjection,
} from "@egjs/react-view360";
import "@egjs/react-view360/css/view360.min.css";

function App() {
  const projection = useMemo(
    () =>
      new EquirectProjection({
        src: require("./assets/Test_360.jpg"),
      }),
    []
  );

  return (
    <View360
      className="is-16by9"
      projection={projection}
      plugins={[
        new ControlBar({
          vrButton: {
            position: ControlBar.POSITION.TOP_RIGHT,
            order: 0,
          },
          gyroButton: {
            position: ControlBar.POSITION.TOP_LEFT,
            order: 0,
          },
        }),
      ]}
    />
  );
}

export default App;
```

EDIT : It appears the buttons show in the html source code but they do not show on my mobile phone when accessing the website, it looks like the class of the controls (gyro and vr) keep the class : .view360-controls-unavailable

With this code, only the PieView is showing but not the vrButton nor the gyroButton unlike the viewer on your demo website.

Do you have any idea where this issue is coming from? Am I doing something wrong or is this an issue with the beta release? 

Thank you in advance,

**Comment by Helyios** [comment]
Indeed, my local server wasn't setup to use secure context. Fixed it. Sorry for the unnecessary issue...

**Comment by WoodNeck** [comment]
You don't have to say sorry, feel free to ask us!
I'll close this issue to mark it as resolved.
