### ISSUE TITLE
Frontend hotspot

### ISSUE THREAD

**Issue by Roxcsas** [naver/egjs-view360#414]
Hi, im using @egjs/ngx-view360: ^4.0.0-beta.5 and im trying to create an interface on front-end where the user can click and make an hotspot but im having problems on getting the position for the hotspot from the click on the canvas.

**Comment by WoodNeck** [comment]
Hello @Roxcsas

First of all, we don't provide API for adding hotspots at the moment, so creating such a feature might be tricky.
But here's how to do it:
- https://codepen.io/woodneck/pen/poxdbZq

It requires module `gl-matrix` additionally, which is actually our dependency so you can just add that to your dependency (simply by installing it).
```sh
npm i --save gl-matrix
```
