### ISSUE TITLE
Change scene by clicking hotspot

### ISSUE THREAD

**Issue by Roxcsas** [naver/egjs-view360#415]
## Description
Hi, im trying to do something like the  [demo](https://naver.github.io/egjs-view360/demo/hotspot#5-change-scene-by-clicking-hotspot) to change scene by clicking hotspot but i can't change the src after the scene its rendered.

**Comment by EarhartZhao** [comment]
Hi bro, did you solve the question. I change the value of projectionOptions.src, but the sence don't change.

**Comment by Roxcsas** [comment]
> Hi bro, did you solve the question. I change the value of projectionOptions.src, but the sence don't change.

nope

**Comment by EarhartZhao** [comment]
I implement this with [https://naver.github.io/egjs-view360/docs/api/Class/View360#event-load]("viewer.load")
