### ISSUE TITLE
EquirectProjection is not a constructor

### ISSUE THREAD

**Issue by CammiePone** [naver/egjs-view360#416]
## Description
Not totally sure what I did wrong, I just followed the steps in the quick start guide for Svelte, but it doesn't really seem to want to work.

![image](https://user-images.githubusercontent.com/16853086/236693427-5c503c1e-4a56-46a2-b52f-fb40e12048b5.png)

## Steps to check or reproduce
Literally just followed the [quick start guide](https://naver.github.io/egjs-view360/docs/quick-start-svelte). The only difference is I used yarn instead of npm to install View360.

**Comment by WoodNeck** [comment]
Hello @CammiePone
Try installing a newer version of the package (`@egjs/svelte-view360@4.0.0-beta.6).
Please tell me if it doesn't work.

**Comment by CammiePone** [comment]
would the `@next` tag have not installed 4.0.0 beta 6? if not, I'll give it a go tomorrow

**Comment by WoodNeck** [comment]
That's because I released `beta.6` just now. I knew the issue & fixed it on 61b2e398f0fd666f949b94820368bb413e4963c4 but postponed releasing it :)

**Comment by CammiePone** [comment]
woo! new problem!

![image](https://user-images.githubusercontent.com/16853086/236824834-8ea61322-3fd3-4524-af2c-ca9975432b52.png)

**Comment by WoodNeck** [comment]
Thanks for reporting, I've created a PR that fixes that :)

**Comment by CammiePone** [comment]
thank you!

**Comment by CammiePone** [comment]
by the way, is View360 able to work with cube panoramas (panoramas made from 6 images)? not relevant to this issue, but thought I may as well ask since I'm not really sure where else to ^^;

**Comment by CammiePone** [comment]
awesome, thank you!

**Comment by rajeevom** [comment]
![image](https://github.com/naver/egjs-view360/assets/79638809/33016f83-0d1a-4249-b418-aac4960a7eb8)
![image](https://github.com/naver/egjs-view360/assets/79638809/c7ba0283-be70-4e65-ab4f-0ccc43078820)

![image](https://github.com/naver/egjs-view360/assets/79638809/4c0980a7-5810-4f99-8fe5-1c4536e91a23)


I am getting same issue

**Comment by rajeevom** [comment]
@WoodNeck
