### ISSUE TITLE
[BUG] view360@3.6.4 does not work in AOS

### ISSUE THREAD

**Issue by njh7799** [naver/egjs-view360#433]
## Description

View360 (ver. @egjs/view360@3.6.4) renders a black image on AOS.

<img width="400px" src="https://github.com/naver/egjs-view360/assets/40619551/6615617b-1567-4ccc-9057-ad40e6d5bbd1" />
<img width="400px" src="https://github.com/naver/egjs-view360/assets/40619551/65fc2b42-10ac-4ca2-860b-5841fe4a82a9" />

<details>
   <summary>works fine on IOS</summary>
   <img width="300px" src="https://github.com/naver/egjs-view360/assets/40619551/23b626d8-c45a-4ea1-b704-7ed711eda3a7"/>
</details>

### Device Info

```
Device: Galaxy S22
OS: Android 12
Browser: Chrome (99.0.4844.88)
```
```
Device: Galaxy S22+
OS: Android 13
Browser: Naver (unkown)
```
```
Device: Galaxy S22
OS: Android 12
Browser: Naver (12.0.2)
```
### Code

```html
<!doctype html>
<html>
  <head>
    <title>JavaScript Sandbox</title>
    <link href="./styles.css" />
  </head>

  <body>
    <div id="myPanoViewer"></div>

    <script src="./index.js" type="module"></script>
  </body>
</html>

```

```js
import { PanoViewer } from "@egjs/view360";

const panoViewer = new PanoViewer(document.getElementById("myPanoViewer"), {
  image: "https://blog.oneunicorn.com/assets/playingminecraft360.jpg",
});
```

reproduction link
- codesandbox: https://codesandbox.io/p/sandbox/heuristic-poincare-rrqx6p
- codepen: https://codepen.io/njh7799/pen/BaMxJww

**Comment by daybrush** [comment]
@njh7799 


Hello. For AOS, the maximum image size is limited to 4096px.

Your image must be at least 9000px. Please check it.

**Comment by njh7799** [comment]
@daybrush

I have confirmed that PanoViewer works fine in AOS when the image size is reduced.

Thank you for your response.
