### ISSUE TITLE
FireFox Script error

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs-view360#57]
## Description
Firefox fires script error.

It is related with https://github.com/naver/egjs-axes/issues/76

**Comment by jongmoon** [comment]
https://github.com/naver/egjs-axes/issues/78 issue is added.

**Comment by happyhj** [comment]
fixed by updating egjs-axes to v2.3.2 in this commit
https://github.com/naver/egjs-view360/commit/cab33de5d95d9ef4627e250792f6d3104dbecb11
