### ISSUE TITLE
Script Errors on IE11 (PanoViewer)

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs-view360#58]
## Description
Fails on IE11

because use of `Object.assign`

Let's deal this with [babel polyfill](https://babeljs.io/docs/plugins/transform-object-assign).

**Comment by happyhj** [comment]
fixed with this commit
https://github.com/naver/egjs-view360/commit/0daeafb9afc1d4d39ed8f6f16794d40039868664#diff-e56633f72ecc521128b3db6586074d2c
