### ISSUE TITLE
When poster is failed to load on video tag, PanoViewer also not work

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-view360#86]
## Steps to check or reproduce
1. Initiate PanoViewer with video tag with invalid(not loadable) poster attribute value.
```
<video id="panorama" poster="/PATH/NOT/EXIST">
    <source src="/VALID/SOURCE/PATH" type="video/mp4"/>
</video>
```
2. PanoViewer will not initiate and trigger error event.

**Comment by jongmoon** [comment]
It's fixed by merging #84
